// Single source of truth for every visible string across all four SAHYOG
// portals. Every page/component reads copy through useLanguage().t("a.b.c")
// - nothing is hardcoded inline.
//
// Language coverage is deliberately uneven, and that's a data-driven choice,
// not an oversight: the citizen-facing namespaces (common, nav, header,
// footer, home, submit, track, transparency, about, status) are translated
// into every language citizens might pick - en, hi, bn, or, ur, sat.
//
// Santali (sat, Ol Chiki script): Bhashini (the primary speech/translation
// backend) has no Santali model at all - confirmed against this project's
// own API key via its discovery endpoint, not a stale assumption - same
// "scope limit of the platform itself" situation bhashini.py documents
// for Mundari, Kurukh, Kharia and Khortha. Unlike those, Santali voice
// recording and translation DO work here: "1.Language normalizer/app/
// services/santali_local.py" routes this one language to self-hosted
// open models (Meta MMS for ASR, NLLB-200 for translation, AI4Bharat's
// Indic Parler-TTS for speech) running in santali-voice-service/ instead.
//
// The staff-portal namespaces (operator, institution, government) are
// English + Hindi only, since operators are government/institution staff,
// not citizens picking their own language - see the LanguageProvider,
// which restricts the *offered* choices per portal, while translate()'s
// fallback-to-English below means nothing breaks even if a staff page is
// somehow viewed with bn/or/ur/sat active.
export const dict = {
  en: {
    common: {
      voiceOn: "Voice replies on",
      voiceOff: "Voice replies off",
      back: "Back",
      next: "Next",
      continue: "Continue",
      submit: "Submit",
      cancel: "Cancel",
      close: "Close",
      loading: "Loading...",
      retry: "Try again",
      optional: "optional",
      required: "required",
      yes: "Yes",
      no: "No",
      edit: "Edit",
      search: "Search",
      viewAll: "View all",
      learnMore: "Learn more",
      errorGeneric: "Something went wrong. Please try again.",
      networkError: "Could not reach the server. Please check your connection and try again.",
      skipToContent: "Skip to main content",
      all: "All",
      pageOf: "Page {page} of {count}",
      adminPortalHeading: "SAHYOG program admin?",
      adminPortalBody: "Staff overseeing every track at once (Track A, Track B, industry, lifecycle, transparency) sign in to the unified Admin Portal instead.",
      adminPortalCta: "Go to the Admin Portal",
    },
    nav: {
      home: "Home",
      report: "Report a Problem",
      track: "Track",
      transparency: "Transparency",
      about: "About",
      language: "Language",
    },
    header: {
      brand: "Sahyog",
      brandSub: "Government of Jharkhand · Grievance Redressal Portal",
      operatorBadge: "DNO Operator Portal",
      institutionBadge: "Institution Portal",
      governmentBadge: "Government Dashboard",
    },
    footer: {
      about: "About Sahyog",
      helpline: "Helpline",
      helplineNumber: "1800-XXX-XXXX (demo)",
      privacy: "Privacy Policy",
      terms: "Terms of Use",
      disclaimer:
        "Sahyog is a demonstration platform built for Smart India Hackathon 2026. It is not yet a live production government service.",
      copyright: "© 2026 Government of Jharkhand. All rights reserved.",
    },
    home: {
      heroTitle: "Sahyog",
      heroTagline: "Your voice, heard and acted upon — for a better Jharkhand.",
      heroSub:
        "Report civic problems in your own language. Our system checks, prioritises and routes every complaint to the right people — and a human always reviews before action is taken.",
      ctaPrimary: "Report a Problem",
      ctaSecondary: "Track a Complaint",
      statsHeading: "Sahyog at a glance",
      statFiled: "Complaints filed",
      statResolved: "Complaints resolved",
      statDistricts: "Districts covered",
      statInstitutions: "Institutions engaged",
      feedHeading: "Recent public complaints",
      feedSubtitle: "A live feed of grievances reported across Jharkhand.",
      filterStatus: "Status",
      filterDistrict: "District",
      filterAllStatuses: "All statuses",
      filterAllDistricts: "All districts",
      feedEmpty: "No complaints match these filters yet.",
      mapHeading: "Where problems are being reported",
      mapCaption: "Approximate locations of recent complaints (for illustration).",
      demoBanner: "Showing sample data — the live backend could not be reached right now.",
    },
    status: {
      registered: "Registered",
      in_progress: "In Progress",
      resolved: "Resolved",
      escalated_track_b: "Escalated to Track B",
      merged: "Merged with existing report",
    },
    submit: {
      wizardTitle: "Report a Problem",
      stepOf: "Step {n} of 5",
      steps: {
        describe: "Describe",
        evidence: "Evidence",
        location: "Location",
        review: "Review",
        done: "Done",
      },
      exitConfirm: "Leaving now will discard this report. Continue?",
      demoNotice:
        "The reporting service could not be reached — you can still try the flow in demo mode, but nothing will be saved.",

      describeHeading: "What's the problem?",
      describeSub: "Describe it in your own words — by typing or by voice. There's no need to pick a category; our system works that out for you.",
      textLabel: "Describe the problem",
      textPlaceholder: "E.g. There is a large pothole on the main road near the market...",
      textHelp: "Write in whichever language is easiest for you.",
      orDivider: "or",
      voiceLabel: "Record instead",
      voiceStart: "Start recording",
      voiceStop: "Stop recording",
      voiceRecording: "Recording...",
      // Shown only when the UI language is Santali (sat) - deliberately
      // left untranslated into Santali itself: Bhashini has no model for
      // it, and I don't have reliable Santali fluency either, so a
      // fabricated translation here would risk being wrong for the exact
      // reader who most needs it to be clear. Falls back to this English
      // text automatically (see lib/dict.js's translate()).
      voiceUnavailableSat: "Voice recording isn't available in Santali yet. Please type your report in the box above instead - it will still be submitted and read by a person.",
      voiceRecorded: "Recording captured",
      voiceUploading: "Uploading your recording...",
      voiceUploadFailed: "Could not upload the recording. Please try typing instead.",
      voiceUnsupported: "Voice recording is not supported in this browser.",
      transcribing: "Transcribing your recording...",
      transcribedLabel: "We heard:",
      analyzing: "Reading your description...",
      understoodHeading: "Here's what we understood",
      understoodDomain: "AI-detected category",
      understoodSeverity: "AI-detected severity",
      understoodEdit: "That's not quite right",
      understoodConfirm: "Yes, that's correct",
      correctionLabel: "Tell us what we got wrong",
      correctionPlaceholder: "Correct the description here...",
      correctionSave: "Save correction",
      validationNeedText: "Please describe the problem or record a voice note.",
      describeSubmit: "Submit →",

      evidenceHeading: "Add a photo",
      evidenceSub: "A clear photo helps our team verify and act on the complaint faster.",
      evidenceCameraOption: "Take a photo now",
      evidenceUploadOption: "Upload from gallery",
      uploadLabel: "Choose a photo",
      uploadHint: "JPG or PNG, taken at the location of the problem.",
      uploadButton: "Upload photo →",
      uploadedAlt: "Uploaded evidence photo",
      removePhoto: "Remove photo",
      photoAnalyzing: "Checking your photo...",
      photoRequired: "Please add a photo to continue.",
      matchWarningHeading: "This looks similar to an existing report",
      matchWarningBody:
        "We found a complaint that may already cover this issue. You can continue anyway, or go back and check.",
      continueAnyway: "Continue anyway",
      tryDifferentPhoto: "Try a different photo",
      cameraStart: "Start camera",
      cameraCapture: "Capture",
      cameraRetake: "Retake",
      cameraUsePhoto: "Use this photo",
      cameraDenied: "Camera access was not available. Please upload a photo from your gallery instead.",
      cameraStarting: "Starting camera...",

      locationHeading: "Where is this happening?",
      locationSub: "Use your current location, or enter the address manually.",
      gpsButton: "Use my current location",
      gpsDetecting: "Detecting your location...",
      gpsSuccess: "Location captured",
      gpsFailed: "Could not detect your location. Please enter the address below.",
      gpsUnsupported: "Location services are not available in this browser.",
      addressLabel: "Address / Landmark",
      addressPlaceholder: "E.g. Near Ranchi Bus Stand, Main Road",
      districtLabel: "District",
      districtPlaceholder: "Select your district",
      locationButton: "Confirm location →",
      locationRequired: "Please share a location or enter an address.",

      reviewHeading: "Review your report",
      reviewSub: "Please check the details before submitting.",
      reviewProblem: "Problem",
      reviewCategory: "AI-detected category",
      reviewPhoto: "Photo",
      reviewLocation: "Location",
      reviewDistrict: "District",
      reviewEditStep: "Edit",
      submitButton: "✓ Submit report",
      submitting: "Submitting your report...",
      submitFailed: "Could not submit the report. Please try again.",

      doneHeading: "Report submitted",
      ticketIdLabel: "Your ticket ID",
      trackButton: "Track this complaint",
      newReportButton: "Report another problem",
      briefHeading: "Here's exactly what we captured",
      briefSub: "This is your report as recorded - keep it for reference.",
      whatNextHeading: "What happens next?",
      whatNextDedup: "Our system checks it isn't a duplicate of an existing complaint.",
      whatNextPriority: "It is automatically assessed and assigned a priority.",
      whatNextHuman: "A human reviewer checks the assessment before anything is finalised.",
      whatNextRoute:
        "It is routed either to your local municipal body (Track A) or, for larger research-driven problems, to a partner institution (Track B).",
    },
    track: {
      searchHeading: "Track your complaint",
      searchSub: "Enter the ticket ID you received when you filed your complaint.",
      ticketIdLabel: "Ticket ID",
      ticketIdPlaceholder: "E.g. JH-2026-0001",
      searchButton: "Track",
      notFound: "No complaint found with this ticket ID. Please check and try again.",
      invalidId: "Please enter a valid ticket ID.",
      backToSearch: "← Search another ticket",
      statusHeading: "Complaint status",
      problemLabel: "Problem",
      categoryLabel: "Category",
      routedToLabel: "Routed to",
      timelineHeading: "Progress",
      timeline: {
        submitted: "Submitted",
        review: "Under Review",
        routed: "Routed",
        inProgress: "In Progress",
        resolved: "Resolved",
      },
      trackALabel: "Track A · Municipal body",
      trackBLabel: "Track B · Research institution",
      reportPhotoLabel: "Photo you submitted",
      reportPhotoAlt: "Photo submitted with this complaint",
      closurePhotoLabel: "Closure photo",
      closurePhotoAlt: "Photo confirming the issue was resolved",
      institutionLabel: "Assigned institution",
      matchStatusLabel: "Match status",
      proposalStatusLabel: "Proposal status",
      milestonesHeading: "Research milestones",
      pilotVerdictLabel: "Pilot verification",
      candidatesHeading: "Universities notified",
      candidatesSub: "Your report's problem brief was sent to these institutions - more than one may be reviewing it.",
      candidatesPrimary: "Collaborating",
    },
    transparency: {
      heading: "Transparency Dashboard",
      sub: "Public, aggregated data on how complaints are handled across Jharkhand.",
      dataNote: "Figures are aggregated and updated periodically. No personal data is shown.",
      statsHeading: "Overview",
      statFiled: "Complaints filed",
      statResolved: "Complaints resolved",
      statDistricts: "Districts covered",
      statInstitutions: "Institutions engaged",
      districtHeading: "Complaints by district",
      categoryHeading: "Complaints by category",
      trackSplitHeading: "Track A vs Track B",
      trackSplitSub: "Municipal handling vs. research-institution handling.",
      resolutionHeading: "Resolution outcomes",
      resolutionPassed: "Verified resolved",
      resolutionFailed: "Verification failed",
      resolutionPending: "Pending verification",
      demoNotice: "Showing sample data — the live backend could not be reached.",
      moreDepthLink: "Looking for department/track-level detail? See the full Government Dashboard.",
    },
    about: {
      heading: "About Sahyog",
      intro:
        "Sahyog is a multilingual, AI-assisted platform that helps citizens of Jharkhand report civic problems and helps the government respond faster and more fairly.",
      howHeading: "How it works",
      howIntro: "AI assists — humans decide. At every stage, automated help is checked by a person before action is taken.",
      step1Title: "1. You describe the problem",
      step1Body:
        "In your own words, in your own language, by typing or by voice. Our system reads or listens and works out the category and how serious it is automatically — you never have to classify it yourself.",
      step2Title: "2. We check for duplicates",
      step2Body:
        "The system compares your report with existing complaints in the same area to avoid multiple tickets for the same problem.",
      step3Title: "3. It is prioritised",
      step3Body:
        "Based on severity, location and category, the complaint is given a priority so urgent issues are not lost in a queue.",
      step4Title: "4. A human reviews, then it is routed",
      step4Body:
        "A trained reviewer checks the assessment. Routine civic issues go to the local municipal body (Track A); larger or research-worthy problems can be routed to a partner academic or research institution (Track B).",
      contactHeading: "Questions or feedback?",
      contactBody: "To check on a complaint you've already filed, use Track your complaint. To report a new civic issue, use Submit a complaint.",
    },

    // Staff-portal namespaces: English + Hindi only (see file header comment).
    operator: {
      portalTitle: "DNO Operator Portal",
      loginHeading: "Operator sign-in",
      loginSub: "For District Nodal Officer staff only.",
      usernameLabel: "Username",
      passwordLabel: "Password",
      loginButton: "Sign in",
      loginInvalid: "Incorrect password. Please try again.",
      loginNote:
        "Sign in with the shared staff password to access the live ticket queue, proxied and authenticated through the Orchestrator.",
      logout: "Sign out",

      queueTitle: "Ticket Queue",
      queueSub: "Tickets awaiting a human validation decision, ordered by priority.",
      filterStatus: "Status",
      filterDistrict: "District",
      filterCategory: "Category",
      filterAllStatuses: "All statuses",
      filterAllCategories: "All categories",
      statTotal: "Total tickets",
      statActive: "Active",
      statAvgPriority: "Avg. priority",
      statOldest: "Oldest ticket age",
      mapHeading: "Where these tickets are",
      mapCaption: "Approximate locations of the tickets currently shown below (respects your filters).",
      colId: "Ticket",
      colCategory: "Category",
      colDescription: "Description",
      colSeverity: "Severity",
      colPriority: "Priority",
      colCluster: "Duplicates",
      colAge: "Age",
      colStatus: "Status",
      colActions: "Actions",
      viewDetail: "Review",
      noTickets: "No tickets match these filters.",
      loadMore: "Load more",
      clusterBadge: "{n} similar reports merged in",
      priorityLabel: "Priority score",

      detailBack: "← Back to queue",
      detailTitle: "Ticket #{id}",
      sectionDescription: "Citizen description",
      sectionEvidence: "Evidence",
      sectionLocation: "Location",
      sectionClassification: "AI classification",
      sectionCluster: "Duplicate cluster",
      clusterNote:
        "{n} incoming report(s) were automatically detected as duplicates of this one and merged in before ever becoming a separate ticket — there is no separate list to review, by design.",
      sectionDecision: "Decision",
      decisionApproveA: "Approve — Track A (Municipal)",
      decisionApproveB: "Approve — Track B (Research institution)",
      decisionRejectMerge: "Reject / Merge as duplicate",
      decisionNotesLabel: "Notes (optional)",
      decisionNotesPlaceholder: "Add any context for this decision...",
      decisionSubmit: "Record decision",
      decisionSuccess: "Decision recorded.",
      decisionError: "Could not record the decision. Please try again.",
      alreadyDecided: "This ticket already has a decision recorded.",
      recalculate: "Recalculate priority",
      recalculating: "Recalculating...",
      recalculateSuccess: "Priority score updated.",
      recalculateError: "Could not recalculate priority.",
      noPhoto: "No photo submitted",
      noAudio: "No voice recording submitted",
      demoNotice: "Showing sample queue data — the live backend could not be reached.",
    },

    institution: {
      portalTitle: "Institution Portal",
      loginHeading: "Institution sign-in",
      loginSub: "For HEI / Track B partner institution staff only.",
      usernameLabel: "Registered email",
      passwordLabel: "Password",
      loginButton: "Sign in",
      loginInvalid: "Incorrect password. Please try again.",
      loginNote:
        "Sign in with the shared staff password to access live match, project, and partner data, proxied and authenticated through the Orchestrator.",
      logout: "Sign out",
      heiOwnLoginHeading: "Signing in as an individual institution?",
      heiOwnLoginBody:
        "This shared password is for SAHYOG program staff overseeing all institutions. If you represent one registered HEI, use your own institution's email and password instead.",
      heiOwnLoginCta: "Go to your institution's own sign-in",

      dashboardTitle: "Dashboard",
      dashboardSub: "Overview of Track B matches, active projects and partner funding for your institution.",
      statTotalMatches: "Total matches",
      statPendingMatches: "Pending matches",
      statAcceptedMatches: "Accepted matches",
      statDeclinedMatches: "Declined matches",
      statActiveProjects: "Awaiting disposition",
      statPartners: "Industry partners",
      statCommittedFunding: "Committed funding",
      recentMatchesHeading: "Recent matches",
      recentProjectsHeading: "Projects awaiting disposition",
      recentPartnersHeading: "Partner funding",
      viewSection: "View section",

      inboxTitle: "Match Inbox",
      inboxSub: "Track B cases matched to your institution by semantic capability matching.",
      colCase: "Case",
      colSimilarity: "Match confidence",
      colStatus: "Status",
      colReceived: "Received",
      actionAccept: "Accept",
      actionDecline: "Decline",
      declineNote: "Declining reroutes this case to the next best-matching institution.",
      noMatches: "No matches waiting right now.",
      filterStatus: "Filter by status",
      filterAllStatuses: "All statuses",
      filterPending: "Pending",
      filterAccepted: "Accepted",
      filterDeclined: "Declined",
      statusProposed: "Pending decision",
      statusAccepted: "Accepted",
      statusDeclined: "Declined",
      mapHeading: "Where these cases are",
      mapCaption: "Approximate locations of the cases currently shown below (respects your filter).",

      caseTitle: "Case #{id}",
      caseBack: "← Back to inbox",
      sectionDescription: "Description",
      sectionEvidence: "Evidence",
      sectionLocation: "Location",
      decisionHeading: "Accept this case?",
      decisionSub: "Accepting lets your institution form a team and submit a solution proposal for this case. Declining reroutes it to the next best-matching institution.",
      decisionError: "Could not record your decision. Please try again.",
      declinedNotice: "This case was declined and has been rerouted to another institution.",
      formTeamHeading: "Form a team",
      formTeamName: "Team name",
      formMentorName: "Faculty mentor name",
      formMentorEmail: "Faculty mentor email",
      formStudents: "Student names (comma-separated)",
      formTeamSubmit: "Form team",
      formTeamError: "Could not form the team. Please try again.",
      proposalHeading: "Submit a solution proposal",
      proposalTitle: "Proposal title",
      proposalSummary: "Proposed solution & research analysis",
      proposalSummaryHelp: "Describe your institution's proposed solution and the research/analysis behind it - root cause, methodology, expected outcome.",
      proposalBudget: "Requested budget (₹)",
      proposalTimeline: "Timeline (weeks)",
      proposalDocument: "Solution document (PDF, optional)",
      proposalDocumentHelp: "Attach a detailed write-up, design, or report as a PDF.",
      proposalSubmit: "Submit proposal",
      proposalSubmitError: "Could not submit the proposal. Please try again.",
      proposalSubmittedHeading: "Proposal submitted",
      proposalSubmittedSub: "Awaiting nodal officer review.",

      projectsTitle: "Active Projects",
      projectsSub: "Approved proposals moving through kickoff, milestones and pilot validation.",
      milestoneKickoff: "Kickoff",
      milestoneMidpoint: "Midpoint",
      milestoneFinal: "Final",
      evaluatorScore: "Evaluator score",
      pilotStatus: "Pilot validation",
      dispositionHeading: "Disposition",
      dispositionNote: "This outcome is always a human decision — it is never assigned automatically.",
      dispositionHandover: "Handed over to ULB/Panchayat",
      dispositionSpinout: "Startup / incubation spin-out",
      dispositionPending: "Awaiting human decision",
      dispositionError: "Could not record the disposition. Please try again.",
      noProjects: "No active projects yet.",
      pilotVerdictPass: "Pilot passed",

      partnersTitle: "Industry Partners",
      partnersSub: "Industry partners matched to your projects, and their funding records.",
      colPartner: "Partner",
      colTier: "IP ownership tier",
      colFunding: "Committed funding",
      fundingNote: "This MVP does not transfer real money or issue legally binding agreements — figures shown are records only.",
      fundingError: "Could not release funds. Please try again.",
      releaseFunds: "Release funds",
      noPartners: "No partners matched yet.",
      demoNotice: "Showing sample data for this demo — see the note on the sign-in screen for why.",
      ledgerCommitted: "Committed",
      ledgerPartiallyReleased: "Partially released",
      ledgerFullyReleased: "Fully released",
      ledgerCancelled: "Cancelled",
    },

    government: {
      overviewTitle: "Government Dashboard",
      overviewSub: "District, department and track-level depth on how complaints are handled across Jharkhand.",
      districtDomainHeading: "District × category breakdown",
      mapHeading: "Where complaints are being filed",
      mapCaption: "Approximate locations of complaints across Jharkhand (most recent 200).",
      heiHeading: "HEI participation",
      heiActive: "Active institutions",
      heiPending: "Pending matches",
      heiDeclined: "Declined matches",
      industryHeading: "Industry engagement",
      industryActive: "Active partners",
      industryPending: "Pending matches",
      industryFunding: "Total committed funding",
      completionHeading: "Pilot completion",
      outcomesHeading: "Outcomes",
      outcomeHandovers: "Handovers to ULB/Panchayat",
      outcomeSpinouts: "Startup spin-outs",
      outcomeTrackAResolved: "Track A resolved",
      demoNotice: "Showing sample data — the live backend could not be reached.",

      auditTitle: "Audit Log",
      auditSub: "A live, filterable view of the platform's append-only audit trail.",
      filterEntityType: "Entity type",
      filterEntityId: "Entity ID",
      filterService: "Service",
      filterFrom: "From date",
      filterTo: "To date",
      colTime: "Time",
      colService: "Service",
      colEntity: "Entity",
      colDomain: "Domain",
      colDescription: "Description",
      colAction: "Action taken",
      colEvent: "Event",
      colActor: "Actor",
      noEvents: "No events match these filters.",
    },
  },

  hi: {
    common: {
      voiceOn: "आवाज़ में जवाब चालू",
      voiceOff: "आवाज़ में जवाब बंद",
      back: "पीछे",
      next: "आगे",
      continue: "जारी रखें",
      submit: "भेजें",
      cancel: "रद्द करें",
      close: "बंद करें",
      loading: "लोड हो रहा है...",
      retry: "फिर से कोशिश करें",
      optional: "वैकल्पिक",
      required: "आवश्यक",
      yes: "हाँ",
      no: "नहीं",
      edit: "संपादित करें",
      search: "खोजें",
      viewAll: "सभी देखें",
      learnMore: "और जानें",
      errorGeneric: "कुछ गड़बड़ हो गई। कृपया फिर से कोशिश करें।",
      networkError: "सर्वर से संपर्क नहीं हो सका। कृपया अपना कनेक्शन जांचें और फिर से कोशिश करें।",
      skipToContent: "मुख्य सामग्री पर जाएं",
      all: "सभी",
      pageOf: "पृष्ठ {page} / {count}",
      adminPortalHeading: "SAHYOG प्रोग्राम एडमिन?",
      adminPortalBody: "सभी ट्रैक (ट्रैक A, ट्रैक B, उद्योग, जीवनचक्र, पारदर्शिता) की एक साथ निगरानी करने वाले स्टाफ इसके बजाय एकीकृत एडमिन पोर्टल में लॉगिन करें।",
      adminPortalCta: "एडमिन पोर्टल पर जाएं",
    },
    nav: {
      home: "मुखपृष्ठ",
      report: "शिकायत दर्ज करें",
      track: "स्थिति देखें",
      transparency: "पारदर्शिता",
      about: "परिचय",
      language: "भाषा",
    },
    header: {
      brand: "सहयोग",
      brandSub: "झारखंड सरकार · शिकायत निवारण पोर्टल",
      operatorBadge: "डीएनओ ऑपरेटर पोर्टल",
      institutionBadge: "संस्थान पोर्टल",
      governmentBadge: "सरकारी डैशबोर्ड",
    },
    footer: {
      about: "सहयोग के बारे में",
      helpline: "हेल्पलाइन",
      helplineNumber: "1800-XXX-XXXX (डेमो)",
      privacy: "गोपनीयता नीति",
      terms: "उपयोग की शर्तें",
      disclaimer:
        "सहयोग, स्मार्ट इंडिया हैकाथॉन 2026 के लिए बनाया गया एक प्रदर्शन (डेमो) प्लेटफ़ॉर्म है। यह अभी सरकार की लाइव सेवा नहीं है।",
      copyright: "© 2026 झारखंड सरकार। सर्वाधिकार सुरक्षित।",
    },
    home: {
      heroTitle: "सहयोग",
      heroTagline: "आपकी आवाज़ सुनी जाएगी, और उस पर काम होगा — एक बेहतर झारखंड के लिए।",
      heroSub:
        "अपनी भाषा में नागरिक समस्याएं दर्ज करें। हमारा सिस्टम हर शिकायत की जांच, प्राथमिकता तय और सही विभाग तक पहुंच सुनिश्चित करता है — और कार्रवाई से पहले हमेशा एक व्यक्ति समीक्षा करता है।",
      ctaPrimary: "शिकायत दर्ज करें",
      ctaSecondary: "शिकायत की स्थिति देखें",
      statsHeading: "एक नज़र में सहयोग",
      statFiled: "दर्ज शिकायतें",
      statResolved: "सुलझाई गई शिकायतें",
      statDistricts: "शामिल ज़िले",
      statInstitutions: "जुड़े संस्थान",
      feedHeading: "हाल की सार्वजनिक शिकायतें",
      feedSubtitle: "झारखंड भर से दर्ज शिकायतों की लाइव सूची।",
      filterStatus: "स्थिति",
      filterDistrict: "ज़िला",
      filterAllStatuses: "सभी स्थितियां",
      filterAllDistricts: "सभी ज़िले",
      feedEmpty: "इन फ़िल्टर से मेल खाती कोई शिकायत नहीं मिली।",
      mapHeading: "समस्याएं कहां दर्ज हो रही हैं",
      mapCaption: "हाल की शिकायतों के अनुमानित स्थान (उदाहरण के लिए)।",
      demoBanner: "नमूना डेटा दिखाया जा रहा है — लाइव सर्वर से अभी संपर्क नहीं हो सका।",
    },
    status: {
      registered: "दर्ज हुई",
      in_progress: "प्रक्रिया में",
      resolved: "सुलझाई गई",
      escalated_track_b: "ट्रैक B को भेजी गई",
      merged: "मौजूदा शिकायत में जोड़ी गई",
    },
    submit: {
      wizardTitle: "शिकायत दर्ज करें",
      stepOf: "चरण {n} / 5",
      steps: {
        describe: "विवरण",
        evidence: "प्रमाण",
        location: "स्थान",
        review: "समीक्षा",
        done: "पूर्ण",
      },
      exitConfirm: "अभी बाहर जाने पर यह शिकायत सुरक्षित नहीं होगी। जारी रखें?",
      demoNotice:
        "शिकायत सेवा से संपर्क नहीं हो सका — आप डेमो मोड में इसे आज़मा सकते हैं, लेकिन कुछ भी सुरक्षित नहीं होगा।",

      describeHeading: "समस्या क्या है?",
      describeSub: "अपने शब्दों में बताएं — टाइप करके या बोलकर। कोई श्रेणी चुनने की ज़रूरत नहीं, हमारा सिस्टम इसे स्वयं समझ लेता है।",
      textLabel: "समस्या का विवरण दें",
      textPlaceholder: "जैसे: बाज़ार के पास मुख्य सड़क पर एक बड़ा गड्ढा है...",
      textHelp: "जो भाषा आपके लिए सबसे आसान हो, उसमें लिखें।",
      orDivider: "या",
      voiceLabel: "इसके बजाय रिकॉर्ड करें",
      voiceStart: "रिकॉर्डिंग शुरू करें",
      voiceStop: "रिकॉर्डिंग रोकें",
      voiceRecording: "रिकॉर्ड हो रहा है...",
      voiceRecorded: "रिकॉर्डिंग हो गई",
      voiceUploading: "आपकी रिकॉर्डिंग अपलोड हो रही है...",
      voiceUploadFailed: "रिकॉर्डिंग अपलोड नहीं हो सकी। कृपया टाइप करके देखें।",
      voiceUnsupported: "इस ब्राउज़र में वॉइस रिकॉर्डिंग समर्थित नहीं है।",
      transcribing: "आपकी रिकॉर्डिंग को लिखा जा रहा है...",
      transcribedLabel: "हमने यह सुना:",
      analyzing: "आपका विवरण पढ़ा जा रहा है...",
      understoodHeading: "हमने यह समझा",
      understoodDomain: "AI-पहचानी श्रेणी",
      understoodSeverity: "AI-पहचानी गंभीरता",
      understoodEdit: "यह सही नहीं है",
      understoodConfirm: "हाँ, यह सही है",
      correctionLabel: "बताएं हमसे कहां गलती हुई",
      correctionPlaceholder: "यहां विवरण ठीक करें...",
      correctionSave: "सुधार सुरक्षित करें",
      validationNeedText: "कृपया समस्या का विवरण लिखें या वॉइस नोट रिकॉर्ड करें।",
      describeSubmit: "भेजें →",

      evidenceHeading: "फोटो जोड़ें",
      evidenceSub: "स्पष्ट फोटो हमारी टीम को शिकायत जल्दी जांचने और कार्रवाई करने में मदद करती है।",
      evidenceCameraOption: "अभी फोटो लें",
      evidenceUploadOption: "गैलरी से अपलोड करें",
      uploadLabel: "फोटो चुनें",
      uploadHint: "JPG या PNG, समस्या वाली जगह पर ली गई।",
      uploadButton: "फोटो अपलोड करें →",
      uploadedAlt: "अपलोड की गई प्रमाण फोटो",
      removePhoto: "फोटो हटाएं",
      photoAnalyzing: "आपकी फोटो जांची जा रही है...",
      photoRequired: "आगे बढ़ने के लिए कृपया एक फोटो जोड़ें।",
      matchWarningHeading: "यह किसी मौजूदा शिकायत जैसी लगती है",
      matchWarningBody:
        "हमें एक ऐसी शिकायत मिली है जो शायद इस समस्या को पहले ही कवर करती हो। आप फिर भी जारी रख सकते हैं, या वापस जाकर देख सकते हैं।",
      continueAnyway: "फिर भी जारी रखें",
      tryDifferentPhoto: "दूसरी फोटो आज़माएं",
      cameraStart: "कैमरा शुरू करें",
      cameraCapture: "फोटो लें",
      cameraRetake: "फिर से लें",
      cameraUsePhoto: "यह फोटो उपयोग करें",
      cameraDenied: "कैमरा उपलब्ध नहीं हो सका। कृपया गैलरी से फोटो अपलोड करें।",
      cameraStarting: "कैमरा शुरू हो रहा है...",

      locationHeading: "यह कहां हो रहा है?",
      locationSub: "अपना वर्तमान स्थान उपयोग करें, या पता खुद लिखें।",
      gpsButton: "मेरा वर्तमान स्थान उपयोग करें",
      gpsDetecting: "आपका स्थान पता किया जा रहा है...",
      gpsSuccess: "स्थान प्राप्त हुआ",
      gpsFailed: "आपका स्थान पता नहीं चल सका। कृपया नीचे पता लिखें।",
      gpsUnsupported: "इस ब्राउज़र में लोकेशन सेवा उपलब्ध नहीं है।",
      addressLabel: "पता / लैंडमार्क",
      addressPlaceholder: "जैसे: रांची बस स्टैंड के पास, मुख्य सड़क",
      districtLabel: "ज़िला",
      districtPlaceholder: "अपना ज़िला चुनें",
      locationButton: "स्थान की पुष्टि करें →",
      locationRequired: "कृपया स्थान साझा करें या पता लिखें।",

      reviewHeading: "अपनी शिकायत की समीक्षा करें",
      reviewSub: "भेजने से पहले कृपया विवरण जांच लें।",
      reviewProblem: "समस्या",
      reviewCategory: "AI-पहचानी श्रेणी",
      reviewPhoto: "फोटो",
      reviewLocation: "स्थान",
      reviewDistrict: "ज़िला",
      reviewEditStep: "संपादित करें",
      submitButton: "✓ शिकायत भेजें",
      submitting: "आपकी शिकायत भेजी जा रही है...",
      submitFailed: "शिकायत भेजी नहीं जा सकी। कृपया फिर कोशिश करें।",

      doneHeading: "शिकायत दर्ज हो गई",
      ticketIdLabel: "आपकी टिकट आईडी",
      trackButton: "इस शिकायत को ट्रैक करें",
      newReportButton: "एक और शिकायत दर्ज करें",
      whatNextHeading: "आगे क्या होगा?",
      whatNextDedup: "हमारा सिस्टम जांचता है कि यह किसी मौजूदा शिकायत की नकल तो नहीं है।",
      whatNextPriority: "इसे स्वचालित रूप से आंका जाता है और प्राथमिकता दी जाती है।",
      whatNextHuman: "अंतिम निर्णय से पहले एक व्यक्ति समीक्षक इस आकलन की जांच करता है।",
      whatNextRoute:
        "इसे या तो आपके स्थानीय नगर निकाय (ट्रैक A) को भेजा जाता है, या बड़ी/शोध-योग्य समस्याओं के लिए किसी साझेदार संस्थान (ट्रैक B) को भेजा जाता है।",
    },
    track: {
      searchHeading: "अपनी शिकायत ट्रैक करें",
      searchSub: "शिकायत दर्ज करते समय मिली टिकट आईडी दर्ज करें।",
      ticketIdLabel: "टिकट आईडी",
      ticketIdPlaceholder: "जैसे: JH-2026-0001",
      searchButton: "ट्रैक करें",
      notFound: "इस टिकट आईडी से कोई शिकायत नहीं मिली। कृपया जांचकर फिर से कोशिश करें।",
      invalidId: "कृपया एक मान्य टिकट आईडी दर्ज करें।",
      backToSearch: "← दूसरी टिकट खोजें",
      statusHeading: "शिकायत की स्थिति",
      problemLabel: "समस्या",
      categoryLabel: "श्रेणी",
      routedToLabel: "भेजी गई",
      timelineHeading: "प्रगति",
      timeline: {
        submitted: "दर्ज हुई",
        review: "समीक्षा में",
        routed: "भेजी गई",
        inProgress: "प्रक्रिया में",
        resolved: "सुलझाई गई",
      },
      trackALabel: "ट्रैक A · नगर निकाय",
      trackBLabel: "ट्रैक B · शोध संस्थान",
      reportPhotoLabel: "आपके द्वारा भेजी गई फोटो",
      reportPhotoAlt: "इस शिकायत के साथ भेजी गई फोटो",
      closurePhotoLabel: "समाधान की फोटो",
      closurePhotoAlt: "समस्या हल होने की पुष्टि करने वाली फोटो",
      institutionLabel: "नियुक्त संस्थान",
      matchStatusLabel: "मिलान स्थिति",
      proposalStatusLabel: "प्रस्ताव स्थिति",
      milestonesHeading: "शोध माइलस्टोन",
      pilotVerdictLabel: "पायलट सत्यापन",
    },
    transparency: {
      heading: "पारदर्शिता डैशबोर्ड",
      sub: "झारखंड भर में शिकायतों के निपटान का सार्वजनिक, संकलित डेटा।",
      dataNote: "आंकड़े समय-समय पर संकलित और अपडेट किए जाते हैं। कोई व्यक्तिगत डेटा नहीं दिखाया जाता।",
      statsHeading: "सारांश",
      statFiled: "दर्ज शिकायतें",
      statResolved: "सुलझाई गई शिकायतें",
      statDistricts: "शामिल ज़िले",
      statInstitutions: "जुड़े संस्थान",
      districtHeading: "ज़िले अनुसार शिकायतें",
      categoryHeading: "श्रेणी अनुसार शिकायतें",
      trackSplitHeading: "ट्रैक A बनाम ट्रैक B",
      trackSplitSub: "नगर निकाय बनाम शोध-संस्थान द्वारा निपटान।",
      resolutionHeading: "समाधान के परिणाम",
      resolutionPassed: "सत्यापित रूप से हल",
      resolutionFailed: "सत्यापन विफल",
      resolutionPending: "सत्यापन लंबित",
      demoNotice: "नमूना डेटा दिखाया जा रहा है — लाइव सर्वर से संपर्क नहीं हो सका।",
      moreDepthLink: "विभाग/ट्रैक स्तर का विस्तृत विवरण चाहिए? पूरा सरकारी डैशबोर्ड देखें।",
    },
    about: {
      heading: "सहयोग के बारे में",
      intro:
        "सहयोग एक बहुभाषी, AI-सहायता प्राप्त मंच है जो झारखंड के नागरिकों को नागरिक समस्याएं दर्ज करने में मदद करता है और सरकार को तेज़ी और निष्पक्षता से जवाब देने में सक्षम बनाता है।",
      howHeading: "यह कैसे काम करता है",
      howIntro: "AI मदद करता है — निर्णय व्यक्ति लेता है। हर चरण पर, स्वचालित सहायता की जांच कार्रवाई से पहले एक व्यक्ति द्वारा की जाती है।",
      step1Title: "1. आप समस्या बताते हैं",
      step1Body:
        "अपने शब्दों में, अपनी भाषा में, टाइप करके या बोलकर। हमारा सिस्टम इसे पढ़ता या सुनता है और श्रेणी व गंभीरता स्वयं तय करता है — आपको इसे स्वयं वर्गीकृत करने की कभी ज़रूरत नहीं।",
      step2Title: "2. हम नकल की जांच करते हैं",
      step2Body:
        "सिस्टम आपकी शिकायत की तुलना उसी क्षेत्र की मौजूदा शिकायतों से करता है ताकि एक ही समस्या के लिए कई टिकट न बनें।",
      step3Title: "3. प्राथमिकता तय होती है",
      step3Body:
        "गंभीरता, स्थान और श्रेणी के आधार पर शिकायत को प्राथमिकता दी जाती है ताकि ज़रूरी मामले कतार में न खो जाएं।",
      step4Title: "4. एक व्यक्ति समीक्षा करता है, फिर भेजी जाती है",
      step4Body:
        "एक प्रशिक्षित समीक्षक आकलन की जांच करता है। सामान्य नागरिक समस्याएं स्थानीय नगर निकाय (ट्रैक A) को जाती हैं; बड़ी या शोध-योग्य समस्याएं किसी साझेदार शैक्षणिक या शोध संस्थान (ट्रैक B) को भेजी जा सकती हैं।",
      contactHeading: "प्रश्न या सुझाव?",
      contactBody: "पहले से दर्ज शिकायत जांचने के लिए 'अपनी शिकायत ट्रैक करें' का उपयोग करें। नई नागरिक समस्या दर्ज करने के लिए 'शिकायत दर्ज करें' का उपयोग करें।",
    },

    operator: {
      portalTitle: "डीएनओ ऑपरेटर पोर्टल",
      loginHeading: "ऑपरेटर लॉगिन",
      loginSub: "केवल जिला नोडल अधिकारी स्टाफ के लिए।",
      usernameLabel: "उपयोगकर्ता नाम",
      passwordLabel: "पासवर्ड",
      loginButton: "लॉगिन करें",
      loginInvalid: "पासवर्ड गलत है। कृपया फिर से कोशिश करें।",
      loginNote:
        "ऑर्केस्ट्रेटर के माध्यम से प्रमाणित लाइव टिकट कतार तक पहुंचने के लिए साझा स्टाफ पासवर्ड से लॉगिन करें।",
      logout: "लॉगआउट करें",

      queueTitle: "टिकट कतार",
      queueSub: "मानव सत्यापन निर्णय की प्रतीक्षा कर रही टिकटें, प्राथमिकता के अनुसार क्रमबद्ध।",
      filterStatus: "स्थिति",
      filterDistrict: "ज़िला",
      filterCategory: "श्रेणी",
      filterAllStatuses: "सभी स्थितियां",
      filterAllCategories: "सभी श्रेणियां",
      statTotal: "कुल टिकटें",
      statActive: "सक्रिय",
      statAvgPriority: "औसत प्राथमिकता",
      statOldest: "सबसे पुरानी टिकट की आयु",
      mapHeading: "ये टिकटें कहाँ हैं",
      mapCaption: "नीचे दिखाई गई टिकटों के अनुमानित स्थान (आपके फ़िल्टर के अनुसार)।",
      colId: "टिकट",
      colCategory: "श्रेणी",
      colDescription: "विवरण",
      colSeverity: "गंभीरता",
      colPriority: "प्राथमिकता",
      colCluster: "डुप्लिकेट",
      colAge: "आयु",
      colStatus: "स्थिति",
      colActions: "कार्रवाई",
      viewDetail: "समीक्षा करें",
      noTickets: "इन फ़िल्टर से मेल खाती कोई टिकट नहीं मिली।",
      loadMore: "और लोड करें",
      clusterBadge: "{n} समान रिपोर्ट इसमें जोड़ी गईं",
      priorityLabel: "प्राथमिकता स्कोर",

      detailBack: "← कतार पर वापस जाएं",
      detailTitle: "टिकट #{id}",
      sectionDescription: "नागरिक का विवरण",
      sectionEvidence: "प्रमाण",
      sectionLocation: "स्थान",
      sectionClassification: "AI वर्गीकरण",
      sectionCluster: "डुप्लिकेट क्लस्टर",
      clusterNote:
        "{n} आने वाली रिपोर्ट(ें) स्वचालित रूप से इसकी डुप्लिकेट पाई गईं और अलग टिकट बनने से पहले ही इसमें जोड़ दी गईं — डिज़ाइन के अनुसार इसकी कोई अलग सूची उपलब्ध नहीं है।",
      sectionDecision: "निर्णय",
      decisionApproveA: "स्वीकृत करें — ट्रैक A (नगर निकाय)",
      decisionApproveB: "स्वीकृत करें — ट्रैक B (शोध संस्थान)",
      decisionRejectMerge: "अस्वीकृत / डुप्लिकेट के रूप में मर्ज करें",
      decisionNotesLabel: "टिप्पणी (वैकल्पिक)",
      decisionNotesPlaceholder: "इस निर्णय के लिए कोई संदर्भ जोड़ें...",
      decisionSubmit: "निर्णय दर्ज करें",
      decisionSuccess: "निर्णय दर्ज कर लिया गया।",
      decisionError: "निर्णय दर्ज नहीं हो सका। कृपया फिर से कोशिश करें।",
      alreadyDecided: "इस टिकट पर पहले से ही एक निर्णय दर्ज है।",
      recalculate: "प्राथमिकता पुनर्गणना करें",
      recalculating: "पुनर्गणना हो रही है...",
      recalculateSuccess: "प्राथमिकता स्कोर अपडेट हो गया।",
      recalculateError: "प्राथमिकता पुनर्गणना नहीं हो सकी।",
      noPhoto: "कोई फोटो नहीं भेजी गई",
      noAudio: "कोई वॉइस रिकॉर्डिंग नहीं भेजी गई",
      demoNotice: "नमूना कतार डेटा दिखाया जा रहा है — लाइव बैकएंड से संपर्क नहीं हो सका।",
    },

    institution: {
      portalTitle: "संस्थान पोर्टल",
      loginHeading: "संस्थान लॉगिन",
      loginSub: "केवल HEI / ट्रैक B साझेदार संस्थान स्टाफ के लिए।",
      usernameLabel: "पंजीकृत ईमेल",
      passwordLabel: "पासवर्ड",
      loginButton: "लॉगिन करें",
      loginInvalid: "पासवर्ड गलत है। कृपया फिर से कोशिश करें।",
      loginNote:
        "ऑर्केस्ट्रेटर के माध्यम से प्रमाणित लाइव मैच, प्रोजेक्ट और पार्टनर डेटा तक पहुंचने के लिए साझा स्टाफ पासवर्ड से लॉगिन करें।",
      logout: "लॉगआउट करें",
      heiOwnLoginHeading: "क्या आप एक व्यक्तिगत संस्थान के रूप में लॉगिन कर रहे हैं?",
      heiOwnLoginBody:
        "यह साझा पासवर्ड सभी संस्थानों की निगरानी करने वाले SAHYOG प्रोग्राम स्टाफ के लिए है। यदि आप एक पंजीकृत HEI का प्रतिनिधित्व करते हैं, तो इसके बजाय अपने संस्थान का अपना ईमेल और पासवर्ड उपयोग करें।",
      heiOwnLoginCta: "अपने संस्थान के अपने लॉगिन पर जाएं",

      dashboardTitle: "डैशबोर्ड",
      dashboardSub: "आपके संस्थान के लिए ट्रैक B मैच, सक्रिय परियोजनाएं और साझेदार फंडिंग का अवलोकन।",
      statTotalMatches: "कुल मैच",
      statPendingMatches: "लंबित मैच",
      statAcceptedMatches: "स्वीकृत मैच",
      statDeclinedMatches: "अस्वीकृत मैच",
      statActiveProjects: "निर्णय की प्रतीक्षा में",
      statPartners: "उद्योग साझेदार",
      statCommittedFunding: "प्रतिबद्ध फंडिंग",
      recentMatchesHeading: "हाल के मैच",
      recentProjectsHeading: "निर्णय की प्रतीक्षा में परियोजनाएं",
      recentPartnersHeading: "साझेदार फंडिंग",
      viewSection: "पूरा भाग देखें",

      inboxTitle: "मैच इनबॉक्स",
      inboxSub: "सिमेंटिक क्षमता मिलान द्वारा आपके संस्थान से मिलाए गए ट्रैक B मामले।",
      colCase: "मामला",
      colSimilarity: "मिलान विश्वास",
      colStatus: "स्थिति",
      colReceived: "प्राप्त हुआ",
      actionAccept: "स्वीकार करें",
      actionDecline: "अस्वीकार करें",
      declineNote: "अस्वीकार करने पर यह मामला अगले सर्वश्रेष्ठ-मिलान संस्थान को भेज दिया जाता है।",
      noMatches: "अभी कोई मैच प्रतीक्षा में नहीं है।",
      filterStatus: "स्थिति के अनुसार फ़िल्टर करें",
      filterAllStatuses: "सभी स्थितियां",
      filterPending: "लंबित",
      filterAccepted: "स्वीकृत",
      filterDeclined: "अस्वीकृत",
      statusProposed: "निर्णय लंबित",
      statusAccepted: "स्वीकृत",
      statusDeclined: "अस्वीकृत",
      mapHeading: "ये मामले कहाँ हैं",
      mapCaption: "नीचे दिखाए गए मामलों के अनुमानित स्थान (आपके फ़िल्टर के अनुसार)।",

      caseTitle: "मामला #{id}",
      caseBack: "← इनबॉक्स पर वापस जाएं",
      sectionDescription: "विवरण",
      sectionEvidence: "प्रमाण",
      sectionLocation: "स्थान",
      decisionHeading: "क्या आप यह मामला स्वीकार करते हैं?",
      decisionSub: "स्वीकार करने पर आपका संस्थान टीम बना सकता है और इस मामले के लिए समाधान प्रस्ताव जमा कर सकता है। अस्वीकार करने पर यह अगले सर्वश्रेष्ठ-मिलान संस्थान को भेज दिया जाता है।",
      decisionError: "आपका निर्णय दर्ज नहीं हो सका। कृपया फिर से कोशिश करें।",
      declinedNotice: "यह मामला अस्वीकृत कर दिया गया है और किसी अन्य संस्थान को भेज दिया गया है।",
      formTeamHeading: "टीम बनाएं",
      formTeamName: "टीम का नाम",
      formMentorName: "फैकल्टी मेंटर का नाम",
      formMentorEmail: "फैकल्टी मेंटर ईमेल",
      formStudents: "छात्रों के नाम (कॉमा से अलग करें)",
      formTeamSubmit: "टीम बनाएं",
      formTeamError: "टीम नहीं बन सकी। कृपया फिर से कोशिश करें।",
      proposalHeading: "समाधान प्रस्ताव जमा करें",
      proposalTitle: "प्रस्ताव शीर्षक",
      proposalSummary: "प्रस्तावित समाधान एवं शोध विश्लेषण",
      proposalSummaryHelp: "अपने संस्थान के प्रस्तावित समाधान और उसके पीछे के शोध/विश्लेषण का वर्णन करें - मूल कारण, पद्धति, अपेक्षित परिणाम।",
      proposalBudget: "अनुरोधित बजट (₹)",
      proposalTimeline: "समयसीमा (सप्ताह)",
      proposalDocument: "समाधान दस्तावेज़ (PDF, वैकल्पिक)",
      proposalDocumentHelp: "विस्तृत लेखन, डिज़ाइन या रिपोर्ट को PDF के रूप में संलग्न करें।",
      proposalSubmit: "प्रस्ताव जमा करें",
      proposalSubmitError: "प्रस्ताव जमा नहीं हो सका। कृपया फिर से कोशिश करें।",
      proposalSubmittedHeading: "प्रस्ताव जमा हो गया",
      proposalSubmittedSub: "नोडल अधिकारी की समीक्षा की प्रतीक्षा है।",

      projectsTitle: "सक्रिय परियोजनाएं",
      projectsSub: "स्वीकृत प्रस्ताव जो शुरुआत, माइलस्टोन और पायलट सत्यापन से गुजर रहे हैं।",
      milestoneKickoff: "शुरुआत",
      milestoneMidpoint: "मध्यबिंदु",
      milestoneFinal: "अंतिम",
      evaluatorScore: "मूल्यांकक स्कोर",
      pilotStatus: "पायलट सत्यापन",
      dispositionHeading: "अंतिम निर्णय",
      dispositionNote: "यह परिणाम हमेशा एक मानव निर्णय होता है — यह कभी स्वचालित रूप से नहीं दिया जाता।",
      dispositionHandover: "ULB/पंचायत को सौंपा गया",
      dispositionSpinout: "स्टार्टअप / इनक्यूबेशन स्पिन-आउट",
      dispositionPending: "मानव निर्णय की प्रतीक्षा में",
      dispositionError: "निर्णय दर्ज नहीं हो सका। कृपया फिर से कोशिश करें।",
      noProjects: "अभी कोई सक्रिय परियोजना नहीं है।",
      pilotVerdictPass: "पायलट सफल",

      partnersTitle: "उद्योग साझेदार",
      partnersSub: "आपकी परियोजनाओं से मिलाए गए उद्योग साझेदार, और उनके फंडिंग रिकॉर्ड।",
      colPartner: "साझेदार",
      colTier: "IP स्वामित्व स्तर",
      colFunding: "प्रतिबद्ध फंडिंग",
      fundingNote: "यह MVP कोई वास्तविक राशि स्थानांतरित नहीं करता और कोई कानूनी रूप से बाध्यकारी अनुबंध जारी नहीं करता — दिखाए गए आंकड़े केवल रिकॉर्ड हैं।",
      fundingError: "राशि जारी नहीं हो सकी। कृपया फिर से कोशिश करें।",
      releaseFunds: "राशि जारी करें",
      noPartners: "अभी कोई साझेदार नहीं मिलाया गया।",
      demoNotice: "इस डेमो के लिए नमूना डेटा दिखाया जा रहा है — कारण जानने के लिए लॉगिन स्क्रीन पर दी गई टिप्पणी देखें।",
      ledgerCommitted: "प्रतिबद्ध",
      ledgerPartiallyReleased: "आंशिक रूप से जारी",
      ledgerFullyReleased: "पूर्ण रूप से जारी",
      ledgerCancelled: "रद्द",
    },

    government: {
      overviewTitle: "सरकारी डैशबोर्ड",
      overviewSub: "झारखंड भर में शिकायतों के निपटान का ज़िला, विभाग और ट्रैक-स्तरीय विस्तृत विवरण।",
      districtDomainHeading: "ज़िला × श्रेणी विवरण",
      mapHeading: "शिकायतें कहाँ दर्ज हो रही हैं",
      mapCaption: "झारखंड भर में शिकायतों के अनुमानित स्थान (नवीनतम 200)।",
      heiHeading: "HEI सहभागिता",
      heiActive: "सक्रिय संस्थान",
      heiPending: "लंबित मैच",
      heiDeclined: "अस्वीकृत मैच",
      industryHeading: "उद्योग सहभागिता",
      industryActive: "सक्रिय साझेदार",
      industryPending: "लंबित मैच",
      industryFunding: "कुल प्रतिबद्ध फंडिंग",
      completionHeading: "पायलट पूर्णता",
      outcomesHeading: "परिणाम",
      outcomeHandovers: "ULB/पंचायत को सौंपे गए",
      outcomeSpinouts: "स्टार्टअप स्पिन-आउट",
      outcomeTrackAResolved: "ट्रैक A हल हुए",
      demoNotice: "नमूना डेटा दिखाया जा रहा है — लाइव बैकएंड से संपर्क नहीं हो सका।",

      auditTitle: "ऑडिट लॉग",
      auditSub: "प्लेटफ़ॉर्म के एपेंड-ओनली ऑडिट ट्रेल का एक लाइव, फ़िल्टर करने योग्य दृश्य।",
      filterEntityType: "एंटिटी प्रकार",
      filterEntityId: "एंटिटी आईडी",
      filterService: "सेवा",
      filterFrom: "तिथि से",
      filterTo: "तिथि तक",
      colTime: "समय",
      colService: "सेवा",
      colEntity: "एंटिटी",
      colDomain: "डोमेन",
      colDescription: "विवरण",
      colAction: "की गई कार्रवाई",
      colEvent: "इवेंट",
      colActor: "कर्ता",
      noEvents: "इन फ़िल्टर से मेल खाती कोई घटना नहीं मिली।",
    },
  },

  bn: {
    common: {
      voiceOn: "ভয়েস উত্তর চালু",
      voiceOff: "ভয়েস উত্তর বন্ধ",
      back: "পিছনে",
      next: "এগিয়ে",
      continue: "চালিয়ে যান",
      submit: "জমা দিন",
      cancel: "বাতিল করুন",
      close: "বন্ধ করুন",
      loading: "লোড হচ্ছে...",
      retry: "আবার চেষ্টা করুন",
      optional: "ঐচ্ছিক",
      required: "আবশ্যক",
      yes: "হ্যাঁ",
      no: "না",
      edit: "সম্পাদনা করুন",
      search: "অনুসন্ধান করুন",
      viewAll: "সব দেখুন",
      learnMore: "আরও জানুন",
      errorGeneric: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।",
      networkError: "সার্ভারের সাথে যোগাযোগ করা যায়নি। অনুগ্রহ করে আপনার সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।",
      skipToContent: "মূল বিষয়বস্তুতে যান",
    },
    nav: {
      home: "হোম",
      report: "সমস্যা জানান",
      track: "ট্র্যাক করুন",
      transparency: "স্বচ্ছতা",
      about: "পরিচিতি",
      language: "ভাষা",
    },
    header: {
      brand: "সহযোগ",
      brandSub: "ঝাড়খণ্ড সরকার · অভিযোগ নিরসন পোর্টাল",
      operatorBadge: "ডিএনও অপারেটর পোর্টাল",
      institutionBadge: "ইনস্টিটিউশন পোর্টাল",
      governmentBadge: "সরকারি ড্যাশবোর্ড",
    },
    footer: {
      about: "সহযোগ সম্পর্কে",
      helpline: "হেল্পলাইন",
      helplineNumber: "1800-XXX-XXXX (ডেমো)",
      privacy: "গোপনীয়তা নীতি",
      terms: "ব্যবহারের শর্তাবলী",
      disclaimer:
        "সহযোগ স্মার্ট ইন্ডিয়া হ্যাকাথন ২০২৬-এর জন্য তৈরি একটি প্রদর্শনী প্ল্যাটফর্ম। এটি এখনও সরকারের লাইভ পরিষেবা নয়।",
      copyright: "© ২০২৬ ঝাড়খণ্ড সরকার। সর্বস্বত্ব সংরক্ষিত।",
    },
    home: {
      heroTitle: "সহযোগ",
      heroTagline: "আপনার কথা শোনা হবে, এবং তার ভিত্তিতে কাজ হবে — একটি উন্নত ঝাড়খণ্ডের জন্য।",
      heroSub:
        "আপনার নিজের ভাষায় নাগরিক সমস্যার অভিযোগ করুন। আমাদের সিস্টেম প্রতিটি অভিযোগ যাচাই করে, অগ্রাধিকার নির্ধারণ করে এবং সঠিক মানুষের কাছে পাঠায় — এবং কোনো ব্যবস্থা নেওয়ার আগে সবসময় একজন মানুষ পর্যালোচনা করেন।",
      ctaPrimary: "সমস্যা জানান",
      ctaSecondary: "অভিযোগ ট্র্যাক করুন",
      statsHeading: "এক নজরে সহযোগ",
      statFiled: "দাখিল করা অভিযোগ",
      statResolved: "সমাধান করা অভিযোগ",
      statDistricts: "অন্তর্ভুক্ত জেলা",
      statInstitutions: "যুক্ত প্রতিষ্ঠান",
      feedHeading: "সাম্প্রতিক জনসাধারণের অভিযোগ",
      feedSubtitle: "ঝাড়খণ্ড জুড়ে দাখিল করা অভিযোগের একটি লাইভ তালিকা।",
      filterStatus: "অবস্থা",
      filterDistrict: "জেলা",
      filterAllStatuses: "সব অবস্থা",
      filterAllDistricts: "সব জেলা",
      feedEmpty: "এই ফিল্টারের সাথে মেলে এমন কোনো অভিযোগ নেই।",
      mapHeading: "কোথায় সমস্যা জানানো হচ্ছে",
      mapCaption: "সাম্প্রতিক অভিযোগের আনুমানিক স্থান (উদাহরণস্বরূপ)।",
      demoBanner: "নমুনা তথ্য দেখানো হচ্ছে — এই মুহূর্তে লাইভ সার্ভারের সাথে যোগাযোগ করা যায়নি।",
    },
    status: {
      registered: "নিবন্ধিত",
      in_progress: "চলমান",
      resolved: "সমাধান হয়েছে",
      escalated_track_b: "ট্র্যাক B-তে পাঠানো হয়েছে",
      merged: "বিদ্যমান অভিযোগের সাথে যুক্ত",
    },
    submit: {
      wizardTitle: "সমস্যা জানান",
      stepOf: "পদক্ষেপ {n} / ৫",
      steps: {
        describe: "বিবরণ",
        evidence: "প্রমাণ",
        location: "স্থান",
        review: "পর্যালোচনা",
        done: "সম্পন্ন",
      },
      exitConfirm: "এখন চলে গেলে এই অভিযোগ সংরক্ষিত হবে না। চালিয়ে যাবেন?",
      demoNotice:
        "অভিযোগ পরিষেবার সাথে যোগাযোগ করা যায়নি — আপনি ডেমো মোডে চেষ্টা করতে পারেন, কিন্তু কিছুই সংরক্ষিত হবে না।",

      describeHeading: "সমস্যাটি কী?",
      describeSub: "আপনার নিজের ভাষায় বলুন — টাইপ করে বা কথা বলে। কোনো বিভাগ বেছে নেওয়ার প্রয়োজন নেই, আমাদের সিস্টেম নিজেই তা বুঝে নেয়।",
      textLabel: "সমস্যার বিবরণ দিন",
      textPlaceholder: "যেমন: বাজারের কাছে মূল সড়কে একটি বড় গর্ত রয়েছে...",
      textHelp: "যে ভাষা আপনার জন্য সহজ, সেই ভাষায় লিখুন।",
      orDivider: "অথবা",
      voiceLabel: "পরিবর্তে রেকর্ড করুন",
      voiceStart: "রেকর্ডিং শুরু করুন",
      voiceStop: "রেকর্ডিং বন্ধ করুন",
      voiceRecording: "রেকর্ড হচ্ছে...",
      voiceRecorded: "রেকর্ডিং সম্পন্ন হয়েছে",
      voiceUploading: "আপনার রেকর্ডিং আপলোড হচ্ছে...",
      voiceUploadFailed: "রেকর্ডিং আপলোড করা যায়নি। দয়া করে টাইপ করে দেখুন।",
      voiceUnsupported: "এই ব্রাউজারে ভয়েস রেকর্ডিং সমর্থিত নয়।",
      transcribing: "আপনার রেকর্ডিং লেখা হচ্ছে...",
      transcribedLabel: "আমরা শুনেছি:",
      analyzing: "আপনার বিবরণ পড়া হচ্ছে...",
      understoodHeading: "আমরা এটি বুঝেছি",
      understoodDomain: "AI-নির্ধারিত বিভাগ",
      understoodSeverity: "AI-নির্ধারিত তীব্রতা",
      understoodEdit: "এটি সঠিক নয়",
      understoodConfirm: "হ্যাঁ, এটি সঠিক",
      correctionLabel: "আমাদের বলুন কোথায় ভুল হয়েছে",
      correctionPlaceholder: "এখানে বিবরণ ঠিক করুন...",
      correctionSave: "সংশোধন সংরক্ষণ করুন",
      validationNeedText: "দয়া করে সমস্যার বিবরণ লিখুন বা একটি ভয়েস নোট রেকর্ড করুন।",
      describeSubmit: "জমা দিন →",

      evidenceHeading: "একটি ছবি যুক্ত করুন",
      evidenceSub: "একটি স্পষ্ট ছবি আমাদের দলকে অভিযোগ যাচাই করতে এবং দ্রুত ব্যবস্থা নিতে সাহায্য করে।",
      evidenceCameraOption: "এখনই ছবি তুলুন",
      evidenceUploadOption: "গ্যালারি থেকে আপলোড করুন",
      uploadLabel: "একটি ছবি বেছে নিন",
      uploadHint: "JPG বা PNG, সমস্যার স্থানে তোলা।",
      uploadButton: "ছবি আপলোড করুন →",
      uploadedAlt: "আপলোড করা প্রমাণ ছবি",
      removePhoto: "ছবি সরান",
      photoAnalyzing: "আপনার ছবি পরীক্ষা করা হচ্ছে...",
      photoRequired: "চালিয়ে যাওয়ার জন্য দয়া করে একটি ছবি যুক্ত করুন।",
      matchWarningHeading: "এটি একটি বিদ্যমান অভিযোগের মতো দেখাচ্ছে",
      matchWarningBody:
        "আমরা এমন একটি অভিযোগ পেয়েছি যা সম্ভবত এই সমস্যাটি ইতিমধ্যেই কভার করে। আপনি চাইলে চালিয়ে যেতে পারেন, বা ফিরে গিয়ে দেখতে পারেন।",
      continueAnyway: "তবুও চালিয়ে যান",
      tryDifferentPhoto: "অন্য একটি ছবি চেষ্টা করুন",
      cameraStart: "ক্যামেরা চালু করুন",
      cameraCapture: "ছবি তুলুন",
      cameraRetake: "আবার তুলুন",
      cameraUsePhoto: "এই ছবিটি ব্যবহার করুন",
      cameraDenied: "ক্যামেরা ব্যবহার করা যায়নি। দয়া করে গ্যালারি থেকে একটি ছবি আপলোড করুন।",
      cameraStarting: "ক্যামেরা চালু হচ্ছে...",

      locationHeading: "এটি কোথায় ঘটছে?",
      locationSub: "আপনার বর্তমান অবস্থান ব্যবহার করুন, বা ঠিকানা নিজে লিখুন।",
      gpsButton: "আমার বর্তমান অবস্থান ব্যবহার করুন",
      gpsDetecting: "আপনার অবস্থান সনাক্ত করা হচ্ছে...",
      gpsSuccess: "অবস্থান পাওয়া গেছে",
      gpsFailed: "আপনার অবস্থান সনাক্ত করা যায়নি। দয়া করে নিচে ঠিকানা লিখুন।",
      gpsUnsupported: "এই ব্রাউজারে লোকেশন পরিষেবা উপলব্ধ নয়।",
      addressLabel: "ঠিকানা / ল্যান্ডমার্ক",
      addressPlaceholder: "যেমন: রাঁচি বাস স্ট্যান্ডের কাছে, মূল সড়ক",
      districtLabel: "জেলা",
      districtPlaceholder: "আপনার জেলা বেছে নিন",
      locationButton: "অবস্থান নিশ্চিত করুন →",
      locationRequired: "দয়া করে একটি অবস্থান শেয়ার করুন বা ঠিকানা লিখুন।",

      reviewHeading: "আপনার অভিযোগ পর্যালোচনা করুন",
      reviewSub: "জমা দেওয়ার আগে দয়া করে বিবরণ যাচাই করুন।",
      reviewProblem: "সমস্যা",
      reviewCategory: "AI-নির্ধারিত বিভাগ",
      reviewPhoto: "ছবি",
      reviewLocation: "অবস্থান",
      reviewDistrict: "জেলা",
      reviewEditStep: "সম্পাদনা করুন",
      submitButton: "✓ অভিযোগ জমা দিন",
      submitting: "আপনার অভিযোগ জমা দেওয়া হচ্ছে...",
      submitFailed: "অভিযোগ জমা দেওয়া যায়নি। দয়া করে আবার চেষ্টা করুন।",

      doneHeading: "অভিযোগ জমা হয়েছে",
      ticketIdLabel: "আপনার টিকিট আইডি",
      trackButton: "এই অভিযোগ ট্র্যাক করুন",
      newReportButton: "আরেকটি সমস্যা জানান",
      whatNextHeading: "এরপর কী হবে?",
      whatNextDedup: "আমাদের সিস্টেম যাচাই করে দেখে যে এটি কোনো বিদ্যমান অভিযোগের প্রতিলিপি নয়।",
      whatNextPriority: "এটি স্বয়ংক্রিয়ভাবে মূল্যায়ন করা হয় এবং একটি অগ্রাধিকার নির্ধারণ করা হয়।",
      whatNextHuman: "কিছু নিশ্চিত হওয়ার আগে একজন মানব পর্যালোচক এই মূল্যায়ন পরীক্ষা করেন।",
      whatNextRoute:
        "এটি হয় আপনার স্থানীয় পৌর সংস্থায় (ট্র্যাক A) পাঠানো হয়, বা বড় গবেষণা-ভিত্তিক সমস্যার জন্য একটি সহযোগী প্রতিষ্ঠানে (ট্র্যাক B) পাঠানো হয়।",
    },
    track: {
      searchHeading: "আপনার অভিযোগ ট্র্যাক করুন",
      searchSub: "অভিযোগ দাখিল করার সময় পাওয়া টিকিট আইডি লিখুন।",
      ticketIdLabel: "টিকিট আইডি",
      ticketIdPlaceholder: "যেমন: JH-2026-0001",
      searchButton: "ট্র্যাক করুন",
      notFound: "এই টিকিট আইডি দিয়ে কোনো অভিযোগ পাওয়া যায়নি। দয়া করে যাচাই করে আবার চেষ্টা করুন।",
      invalidId: "দয়া করে একটি বৈধ টিকিট আইডি লিখুন।",
      backToSearch: "← অন্য টিকিট খুঁজুন",
      statusHeading: "অভিযোগের অবস্থা",
      problemLabel: "সমস্যা",
      categoryLabel: "বিভাগ",
      routedToLabel: "পাঠানো হয়েছে",
      timelineHeading: "অগ্রগতি",
      timeline: {
        submitted: "জমা হয়েছে",
        review: "পর্যালোচনায় রয়েছে",
        routed: "পাঠানো হয়েছে",
        inProgress: "চলমান",
        resolved: "সমাধান হয়েছে",
      },
      trackALabel: "ট্র্যাক A · পৌর সংস্থা",
      trackBLabel: "ট্র্যাক B · গবেষণা প্রতিষ্ঠান",
      reportPhotoLabel: "আপনার পাঠানো ছবি",
      reportPhotoAlt: "এই অভিযোগের সাথে পাঠানো ছবি",
      closurePhotoLabel: "সমাধানের ছবি",
      closurePhotoAlt: "সমস্যা সমাধানের নিশ্চয়তা দেওয়া ছবি",
      institutionLabel: "নিযুক্ত প্রতিষ্ঠান",
      matchStatusLabel: "মিল স্থিতি",
      proposalStatusLabel: "প্রস্তাবের স্থিতি",
      milestonesHeading: "গবেষণা মাইলফলক",
      pilotVerdictLabel: "পাইলট যাচাইকরণ",
    },
    transparency: {
      heading: "স্বচ্ছতা ড্যাশবোর্ড",
      sub: "ঝাড়খণ্ড জুড়ে অভিযোগ কীভাবে পরিচালিত হয় তার সর্বজনীন, সংকলিত তথ্য।",
      dataNote: "পরিসংখ্যান সময়ে সময়ে সংকলিত এবং আপডেট করা হয়। কোনো ব্যক্তিগত তথ্য দেখানো হয় না।",
      statsHeading: "সারসংক্ষেপ",
      statFiled: "দাখিল করা অভিযোগ",
      statResolved: "সমাধান করা অভিযোগ",
      statDistricts: "অন্তর্ভুক্ত জেলা",
      statInstitutions: "যুক্ত প্রতিষ্ঠান",
      districtHeading: "জেলা অনুযায়ী অভিযোগ",
      categoryHeading: "বিভাগ অনুযায়ী অভিযোগ",
      trackSplitHeading: "ট্র্যাক A বনাম ট্র্যাক B",
      trackSplitSub: "পৌর সংস্থা বনাম গবেষণা প্রতিষ্ঠানের মাধ্যমে পরিচালনা।",
      resolutionHeading: "সমাধানের ফলাফল",
      resolutionPassed: "যাচাইকৃতভাবে সমাধান হয়েছে",
      resolutionFailed: "যাচাই ব্যর্থ হয়েছে",
      resolutionPending: "যাচাই অপেক্ষমাণ",
      demoNotice: "নমুনা তথ্য দেখানো হচ্ছে — লাইভ সার্ভারের সাথে যোগাযোগ করা যায়নি।",
      moreDepthLink: "বিভাগ/ট্র্যাক-স্তরের বিস্তারিত তথ্য খুঁজছেন? সম্পূর্ণ সরকারি ড্যাশবোর্ড দেখুন।",
    },
    about: {
      heading: "সহযোগ সম্পর্কে",
      intro:
        "সহযোগ একটি বহুভাষিক, AI-সহায়তাপ্রাপ্ত প্ল্যাটফর্ম যা ঝাড়খণ্ডের নাগরিকদের নাগরিক সমস্যা জানাতে সাহায্য করে এবং সরকারকে দ্রুত ও ন্যায্যভাবে সাড়া দিতে সক্ষম করে।",
      howHeading: "এটি কীভাবে কাজ করে",
      howIntro: "AI সাহায্য করে — মানুষ সিদ্ধান্ত নেয়। প্রতিটি পর্যায়ে, কোনো ব্যবস্থা নেওয়ার আগে স্বয়ংক্রিয় সহায়তা একজন ব্যক্তি দ্বারা পরীক্ষা করা হয়।",
      step1Title: "১. আপনি সমস্যাটি বর্ণনা করেন",
      step1Body:
        "আপনার নিজের ভাষায়, নিজের কথায়, টাইপ করে বা কথা বলে। আমাদের সিস্টেম এটি পড়ে বা শোনে এবং বিভাগ ও তীব্রতা স্বয়ংক্রিয়ভাবে নির্ধারণ করে — আপনাকে কখনো নিজে এটি শ্রেণীবদ্ধ করতে হয় না।",
      step2Title: "২. আমরা প্রতিলিপি পরীক্ষা করি",
      step2Body:
        "একই সমস্যার জন্য একাধিক টিকিট এড়াতে সিস্টেম আপনার অভিযোগকে একই এলাকার বিদ্যমান অভিযোগের সাথে তুলনা করে।",
      step3Title: "৩. অগ্রাধিকার নির্ধারণ করা হয়",
      step3Body:
        "তীব্রতা, স্থান এবং বিভাগের উপর ভিত্তি করে অভিযোগকে একটি অগ্রাধিকার দেওয়া হয়, যাতে জরুরি বিষয়গুলি সারিতে হারিয়ে না যায়।",
      step4Title: "৪. একজন মানুষ পর্যালোচনা করেন, তারপর পাঠানো হয়",
      step4Body:
        "একজন প্রশিক্ষিত পর্যালোচক মূল্যায়ন পরীক্ষা করেন। সাধারণ নাগরিক সমস্যাগুলি স্থানীয় পৌর সংস্থায় (ট্র্যাক A) যায়; বড় বা গবেষণা-উপযোগী সমস্যাগুলি একটি সহযোগী শিক্ষাগত বা গবেষণা প্রতিষ্ঠানে (ট্র্যাক B) পাঠানো যেতে পারে।",
      contactHeading: "প্রশ্ন বা মতামত?",
      contactBody: "ইতিমধ্যে দায়ের করা অভিযোগ পরীক্ষা করতে 'আপনার অভিযোগ ট্র্যাক করুন' ব্যবহার করুন। নতুন নাগরিক সমস্যা রিপোর্ট করতে 'অভিযোগ জমা দিন' ব্যবহার করুন।",
    },
  },

  or: {
    common: {
      voiceOn: "ଭଏସ୍ ଉତ୍ତର ଚାଲୁ",
      voiceOff: "ଭଏସ୍ ଉତ୍ତର ବନ୍ଦ",
      back: "ପଛକୁ",
      next: "ଆଗକୁ",
      continue: "ଜାରି ରଖନ୍ତୁ",
      submit: "ଦାଖଲ କରନ୍ତୁ",
      cancel: "ବାତିଲ୍ କରନ୍ତୁ",
      close: "ବନ୍ଦ କରନ୍ତୁ",
      loading: "ଲୋଡ୍ ହେଉଛି...",
      retry: "ପୁନଃ ପ୍ରୟାସ କରନ୍ତୁ",
      optional: "ଇଚ୍ଛାଧୀନ",
      required: "ଆବଶ୍ୟକ",
      yes: "ହଁ",
      no: "ନାହିଁ",
      edit: "ସମ୍ପାଦନ କରନ୍ତୁ",
      search: "ଖୋଜନ୍ତୁ",
      viewAll: "ସବୁ ଦେଖନ୍ତୁ",
      learnMore: "ଅଧିକ ଜାଣନ୍ତୁ",
      errorGeneric: "କିଛି ଭୁଲ ହୋଇଗଲା। ଦୟାକରି ପୁନଃ ପ୍ରୟାସ କରନ୍ତୁ।",
      networkError: "ସର୍ଭର ସହିତ ସମ୍ପର୍କ ହୋଇପାରିଲା ନାହିଁ। ଦୟାକରି ଆପଣଙ୍କର ସଂଯୋଗ ଯାଞ୍ଚ କରି ପୁନଃ ପ୍ରୟାସ କରନ୍ତୁ।",
      skipToContent: "ମୁଖ୍ୟ ବିଷୟବସ୍ତୁକୁ ଯାଆନ୍ତୁ",
    },
    nav: {
      home: "ମୂଳପୃଷ୍ଠା",
      report: "ସମସ୍ୟା ଜଣାନ୍ତୁ",
      track: "ଟ୍ରାକ୍ କରନ୍ତୁ",
      transparency: "ସ୍ୱଚ୍ଛତା",
      about: "ପରିଚୟ",
      language: "ଭାଷା",
    },
    header: {
      brand: "ସହଯୋଗ",
      brandSub: "ଝାରଖଣ୍ଡ ସରକାର · ଅଭିଯୋଗ ନିରାକରଣ ପୋର୍ଟାଲ",
      operatorBadge: "DNO ଅପରେଟର୍ ପୋର୍ଟାଲ",
      institutionBadge: "ଅନୁଷ୍ଠାନ ପୋର୍ଟାଲ",
      governmentBadge: "ସରକାରୀ ଡ୍ୟାସବୋର୍ଡ",
    },
    footer: {
      about: "ସହଯୋଗ ବିଷୟରେ",
      helpline: "ହେଲ୍ପଲାଇନ୍",
      helplineNumber: "1800-XXX-XXXX (ଡେମୋ)",
      privacy: "ଗୋପନୀୟତା ନୀତି",
      terms: "ବ୍ୟବହାର ସର୍ତ୍ତାବଳୀ",
      disclaimer:
        "ସହଯୋଗ ସ୍ମାର୍ଟ ଇଣ୍ଡିଆ ହ୍ୟାକାଥନ ୨୦୨୬ ପାଇଁ ତିଆରି ହୋଇଥିବା ଏକ ପ୍ରଦର୍ଶନ ପ୍ଲାଟଫର୍ମ। ଏହା ଏପର୍ଯ୍ୟନ୍ତ ସରକାରର ଲାଇଭ୍ ସେବା ନୁହେଁ।",
      copyright: "© ୨୦୨୬ ଝାରଖଣ୍ଡ ସରକାର। ସର୍ବସ୍ୱାମୀତ୍ୱ ସଂରକ୍ଷିତ।",
    },
    home: {
      heroTitle: "ସହଯୋଗ",
      heroTagline: "ଆପଣଙ୍କ ସ୍ୱର ଶୁଣାଯିବ, ଏବଂ ତା' ଉପରେ କାର୍ଯ୍ୟ ହେବ — ଏକ ଉନ୍ନତ ଝାରଖଣ୍ଡ ପାଇଁ।",
      heroSub:
        "ଆପଣଙ୍କ ନିଜ ଭାଷାରେ ନାଗରିକ ସମସ୍ୟାର ଅଭିଯୋଗ କରନ୍ତୁ। ଆମର ସିଷ୍ଟମ୍ ପ୍ରତ୍ୟେକ ଅଭିଯୋଗକୁ ଯାଞ୍ଚ କରେ, ପ୍ରାଧାନ୍ୟ ନିର୍ଣ୍ଣୟ କରେ ଏବଂ ସଠିକ୍ ଲୋକ ପାଖରେ ପହଞ୍ଚାଏ — ଏବଂ କୌଣସି କାର୍ଯ୍ୟାନୁଷ୍ଠାନ ପୂର୍ବରୁ ସର୍ବଦା ଏକ ମାନବ ସମୀକ୍ଷା କରନ୍ତି।",
      ctaPrimary: "ସମସ୍ୟା ଜଣାନ୍ତୁ",
      ctaSecondary: "ଅଭିଯୋଗ ଟ୍ରାକ୍ କରନ୍ତୁ",
      statsHeading: "ଏକ ନଜରରେ ସହଯୋଗ",
      statFiled: "ଦାଖଲ ହୋଇଥିବା ଅଭିଯୋଗ",
      statResolved: "ସମାଧାନ ହୋଇଥିବା ଅଭିଯୋଗ",
      statDistricts: "ଅନ୍ତର୍ଭୁକ୍ତ ଜିଲ୍ଲା",
      statInstitutions: "ଯୋଡ଼ି ହୋଇଥିବା ଅନୁଷ୍ଠାନ",
      feedHeading: "ସାମ୍ପ୍ରତିକ ସାର୍ବଜନୀନ ଅଭିଯୋଗ",
      feedSubtitle: "ଝାରଖଣ୍ଡ ସାରା ଦାଖଲ ହୋଇଥିବା ଅଭିଯୋଗର ଏକ ଲାଇଭ୍ ତାଲିକା।",
      filterStatus: "ସ୍ଥିତି",
      filterDistrict: "ଜିଲ୍ଲା",
      filterAllStatuses: "ସମସ୍ତ ସ୍ଥିତି",
      filterAllDistricts: "ସମସ୍ତ ଜିଲ୍ଲା",
      feedEmpty: "ଏହି ଫିଲ୍ଟର ସହିତ ମେଳ ଖାଉଥିବା କୌଣସି ଅଭିଯୋଗ ନାହିଁ।",
      mapHeading: "କେଉଁଠାରେ ସମସ୍ୟା ଜଣାଯାଉଛି",
      mapCaption: "ସାମ୍ପ୍ରତିକ ଅଭିଯୋଗର ଆନୁମାନିକ ସ୍ଥାନ (ଉଦାହରଣ ପାଇଁ)।",
      demoBanner: "ନମୁନା ତଥ୍ୟ ଦେଖାଯାଉଛି — ବର୍ତ୍ତମାନ ଲାଇଭ୍ ସର୍ଭର ସହିତ ସମ୍ପର୍କ ହୋଇପାରିଲା ନାହିଁ।",
    },
    status: {
      registered: "ପଞ୍ଜୀକୃତ",
      in_progress: "ଚାଲୁ ଅଛି",
      resolved: "ସମାଧାନ ହୋଇଗଲା",
      escalated_track_b: "ଟ୍ରାକ୍ Bକୁ ପଠାଗଲା",
      merged: "ପୂର୍ବ ଅଭିଯୋଗ ସହିତ ମିଶାଗଲା",
    },
    submit: {
      wizardTitle: "ସମସ୍ୟା ଜଣାନ୍ତୁ",
      stepOf: "ପାହାଚ {n} / ୫",
      steps: {
        describe: "ବିବରଣୀ",
        evidence: "ପ୍ରମାଣ",
        location: "ସ୍ଥାନ",
        review: "ସମୀକ୍ଷା",
        done: "ସମ୍ପୂର୍ଣ୍ଣ",
      },
      exitConfirm: "ବର୍ତ୍ତମାନ ଚାଲିଗଲେ ଏହି ଅଭିଯୋଗ ସାଇତି ହେବ ନାହିଁ। ଜାରି ରଖିବେ?",
      demoNotice:
        "ଅଭିଯୋଗ ସେବା ସହିତ ସମ୍ପର୍କ ହୋଇପାରିଲା ନାହିଁ — ଆପଣ ଡେମୋ ମୋଡ୍‌ରେ ଚେଷ୍ଟା କରିପାରିବେ, କିନ୍ତୁ କିଛି ସାଇତି ହେବ ନାହିଁ।",

      describeHeading: "ସମସ୍ୟାଟି କ'ଣ?",
      describeSub: "ଆପଣଙ୍କ ନିଜ ଭାଷାରେ କୁହନ୍ତୁ — ଟାଇପ୍ କରି କିମ୍ବା କହି। କୌଣସି ବିଭାଗ ବାଛିବାର ଆବଶ୍ୟକତା ନାହିଁ, ଆମର ସିଷ୍ଟମ୍ ନିଜେ ତାହା ବୁଝିଯାଏ।",
      textLabel: "ସମସ୍ୟାର ବିବରଣୀ ଦିଅନ୍ତୁ",
      textPlaceholder: "ଯେମିତି: ବଜାର ପାଖରେ ମୁଖ୍ୟ ସଡ଼କରେ ଏକ ବଡ଼ ଖାଲ ଅଛି...",
      textHelp: "ଯେଉଁ ଭାଷା ଆପଣଙ୍କ ପାଇଁ ସହଜ, ସେହି ଭାଷାରେ ଲେଖନ୍ତୁ।",
      orDivider: "କିମ୍ବା",
      voiceLabel: "ଏହା ପରିବର୍ତ୍ତେ ରେକର୍ଡ କରନ୍ତୁ",
      voiceStart: "ରେକର୍ଡିଂ ଆରମ୍ଭ କରନ୍ତୁ",
      voiceStop: "ରେକର୍ଡିଂ ବନ୍ଦ କରନ୍ତୁ",
      voiceRecording: "ରେକର୍ଡ ହେଉଛି...",
      voiceRecorded: "ରେକର୍ଡିଂ ସମ୍ପୂର୍ଣ୍ଣ ହେଲା",
      voiceUploading: "ଆପଣଙ୍କ ରେକର୍ଡିଂ ଅପଲୋଡ୍ ହେଉଛି...",
      voiceUploadFailed: "ରେକର୍ଡିଂ ଅପଲୋଡ୍ ହୋଇପାରିଲା ନାହିଁ। ଦୟାକରି ଟାଇପ୍ କରି ଦେଖନ୍ତୁ।",
      voiceUnsupported: "ଏହି ବ୍ରାଉଜରରେ ଭଏସ୍ ରେକର୍ଡିଂ ସମର୍ଥିତ ନାହିଁ।",
      transcribing: "ଆପଣଙ୍କ ରେକର୍ଡିଂ ଲେଖାଯାଉଛି...",
      transcribedLabel: "ଆମେ ଏହା ଶୁଣିଲୁ:",
      analyzing: "ଆପଣଙ୍କ ବିବରଣୀ ପଢ଼ାଯାଉଛି...",
      understoodHeading: "ଆମେ ଏହା ବୁଝିଲୁ",
      understoodDomain: "AI-ନିର୍ଣ୍ଣୀତ ବିଭାଗ",
      understoodSeverity: "AI-ନିର୍ଣ୍ଣୀତ ଗମ୍ଭୀରତା",
      understoodEdit: "ଏହା ଠିକ୍ ନାହିଁ",
      understoodConfirm: "ହଁ, ଏହା ଠିକ୍",
      correctionLabel: "ଆମକୁ କୁହନ୍ତୁ କେଉଁଠାରେ ଭୁଲ ହେଲା",
      correctionPlaceholder: "ଏଠାରେ ବିବରଣୀ ଠିକ୍ କରନ୍ତୁ...",
      correctionSave: "ସୁଧାର ସାଇତନ୍ତୁ",
      validationNeedText: "ଦୟାକରି ସମସ୍ୟାର ବିବରଣୀ ଲେଖନ୍ତୁ କିମ୍ବା ଏକ ଭଏସ୍ ନୋଟ୍ ରେକର୍ଡ କରନ୍ତୁ।",
      describeSubmit: "ଦାଖଲ କରନ୍ତୁ →",

      evidenceHeading: "ଏକ ଫଟୋ ଯୋଡ଼ନ୍ତୁ",
      evidenceSub: "ଏକ ସ୍ପଷ୍ଟ ଫଟୋ ଆମ ଦଳକୁ ଅଭିଯୋଗ ଯାଞ୍ଚ କରି ଶୀଘ୍ର କାର୍ଯ୍ୟାନୁଷ୍ଠାନ ନେବାରେ ସାହାଯ୍ୟ କରେ।",
      evidenceCameraOption: "ବର୍ତ୍ତମାନ ଫଟୋ ନିଅନ୍ତୁ",
      evidenceUploadOption: "ଗ୍ୟାଲେରୀରୁ ଅପଲୋଡ୍ କରନ୍ତୁ",
      uploadLabel: "ଏକ ଫଟୋ ବାଛନ୍ତୁ",
      uploadHint: "JPG କିମ୍ବା PNG, ସମସ୍ୟା ସ୍ଥାନରେ ନିଆଯାଇଥିବା।",
      uploadButton: "ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ →",
      uploadedAlt: "ଅପଲୋଡ୍ ହୋଇଥିବା ପ୍ରମାଣ ଫଟୋ",
      removePhoto: "ଫଟୋ ହଟାନ୍ତୁ",
      photoAnalyzing: "ଆପଣଙ୍କ ଫଟୋ ଯାଞ୍ଚ ହେଉଛି...",
      photoRequired: "ଜାରି ରହିବାକୁ ଦୟାକରି ଏକ ଫଟୋ ଯୋଡ଼ନ୍ତୁ।",
      matchWarningHeading: "ଏହା ଏକ ପୂର୍ବ ଅଭିଯୋଗ ଭଳି ଦେଖାଯାଉଛି",
      matchWarningBody:
        "ଆମେ ଏକ ଅଭିଯୋଗ ପାଇଲୁ ଯାହା ସମ୍ଭବତଃ ଏହି ସମସ୍ୟାକୁ ପୂର୍ବରୁ କଭର୍ କରିସାରିଛି। ଆପଣ ତଥାପି ଜାରି ରଖିପାରିବେ, କିମ୍ବା ପଛକୁ ଯାଇ ଯାଞ୍ଚ କରିପାରିବେ।",
      continueAnyway: "ତଥାପି ଜାରି ରଖନ୍ତୁ",
      tryDifferentPhoto: "ଏକ ଭିନ୍ନ ଫଟୋ ଚେଷ୍ଟା କରନ୍ତୁ",
      cameraStart: "କ୍ୟାମେରା ଆରମ୍ଭ କରନ୍ତୁ",
      cameraCapture: "ଫଟୋ ନିଅନ୍ତୁ",
      cameraRetake: "ପୁନଃ ନିଅନ୍ତୁ",
      cameraUsePhoto: "ଏହି ଫଟୋ ବ୍ୟବହାର କରନ୍ତୁ",
      cameraDenied: "କ୍ୟାମେରା ଉପଲବ୍ଧ ହୋଇପାରିଲା ନାହିଁ। ଦୟାକରି ଗ୍ୟାଲେରୀରୁ ଏକ ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ।",
      cameraStarting: "କ୍ୟାମେରା ଆରମ୍ଭ ହେଉଛି...",

      locationHeading: "ଏହା କେଉଁଠାରେ ଘଟୁଛି?",
      locationSub: "ଆପଣଙ୍କ ବର୍ତ୍ତମାନ ସ୍ଥାନ ବ୍ୟବହାର କରନ୍ତୁ, କିମ୍ବା ପତା ନିଜେ ଲେଖନ୍ତୁ।",
      gpsButton: "ମୋର ବର୍ତ୍ତମାନ ସ୍ଥାନ ବ୍ୟବହାର କରନ୍ତୁ",
      gpsDetecting: "ଆପଣଙ୍କ ସ୍ଥାନ ଚିହ୍ନଟ ହେଉଛି...",
      gpsSuccess: "ସ୍ଥାନ ମିଳିଗଲା",
      gpsFailed: "ଆପଣଙ୍କ ସ୍ଥାନ ଚିହ୍ନଟ ହୋଇପାରିଲା ନାହିଁ। ଦୟାକରି ତଳେ ପତା ଲେଖନ୍ତୁ।",
      gpsUnsupported: "ଏହି ବ୍ରାଉଜରରେ ଲୋକେସନ୍ ସେବା ଉପଲବ୍ଧ ନାହିଁ।",
      addressLabel: "ପତା / ଚିହ୍ନସ୍ଥଳ",
      addressPlaceholder: "ଯେମିତି: ରାଞ୍ଚି ବସ୍ ଷ୍ଟାଣ୍ଡ ପାଖରେ, ମୁଖ୍ୟ ସଡ଼କ",
      districtLabel: "ଜିଲ୍ଲା",
      districtPlaceholder: "ଆପଣଙ୍କ ଜିଲ୍ଲା ବାଛନ୍ତୁ",
      locationButton: "ସ୍ଥାନ ନିଶ୍ଚିତ କରନ୍ତୁ →",
      locationRequired: "ଦୟାକରି ଏକ ସ୍ଥାନ ସେୟାର୍ କରନ୍ତୁ କିମ୍ବା ପତା ଲେଖନ୍ତୁ।",

      reviewHeading: "ଆପଣଙ୍କ ଅଭିଯୋଗ ସମୀକ୍ଷା କରନ୍ତୁ",
      reviewSub: "ଦାଖଲ କରିବା ପୂର୍ବରୁ ଦୟାକରି ବିବରଣୀ ଯାଞ୍ଚ କରନ୍ତୁ।",
      reviewProblem: "ସମସ୍ୟା",
      reviewCategory: "AI-ନିର୍ଣ୍ଣୀତ ବିଭାଗ",
      reviewPhoto: "ଫଟୋ",
      reviewLocation: "ସ୍ଥାନ",
      reviewDistrict: "ଜିଲ୍ଲା",
      reviewEditStep: "ସମ୍ପାଦନ କରନ୍ତୁ",
      submitButton: "✓ ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ",
      submitting: "ଆପଣଙ୍କ ଅଭିଯୋଗ ଦାଖଲ ହେଉଛି...",
      submitFailed: "ଅଭିଯୋଗ ଦାଖଲ ହୋଇପାରିଲା ନାହିଁ। ଦୟାକରି ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ।",

      doneHeading: "ଅଭିଯୋଗ ଦାଖଲ ହେଲା",
      ticketIdLabel: "ଆପଣଙ୍କ ଟିକେଟ୍ ଆଇଡି",
      trackButton: "ଏହି ଅଭିଯୋଗ ଟ୍ରାକ୍ କରନ୍ତୁ",
      newReportButton: "ଏକ ଅଧିକ ସମସ୍ୟା ଜଣାନ୍ତୁ",
      whatNextHeading: "ପରେ କ'ଣ ହେବ?",
      whatNextDedup: "ଆମର ସିଷ୍ଟମ୍ ଯାଞ୍ଚ କରେ ଏହା କୌଣସି ପୂର୍ବ ଅଭିଯୋଗର ନକଲ ନୁହେଁ।",
      whatNextPriority: "ଏହାକୁ ସ୍ୱୟଂଚାଳିତ ଭାବରେ ମୂଲ୍ୟାୟନ କରାଯାଇ ଏକ ପ୍ରାଧାନ୍ୟ ଦିଆଯାଏ।",
      whatNextHuman: "କିଛି ଅନ୍ତିମ ହେବା ପୂର୍ବରୁ ଏକ ମାନବ ସମୀକ୍ଷକ ଏହି ମୂଲ୍ୟାୟନ ଯାଞ୍ଚ କରନ୍ତି।",
      whatNextRoute:
        "ଏହା ଆପଣଙ୍କ ସ୍ଥାନୀୟ ନଗର ନିଗମ (ଟ୍ରାକ୍ A) କୁ ପଠାଯାଏ, ଅଥବା ବଡ଼ ଗବେଷଣା-ଆଧାରିତ ସମସ୍ୟା ପାଇଁ ଏକ ସହଭାଗୀ ଅନୁଷ୍ଠାନ (ଟ୍ରାକ୍ B) କୁ ପଠାଯାଏ।",
    },
    track: {
      searchHeading: "ଆପଣଙ୍କ ଅଭିଯୋଗ ଟ୍ରାକ୍ କରନ୍ତୁ",
      searchSub: "ଅଭିଯୋଗ ଦାଖଲ କରିବା ସମୟରେ ମିଳିଥିବା ଟିକେଟ୍ ଆଇଡି ଲେଖନ୍ତୁ।",
      ticketIdLabel: "ଟିକେଟ୍ ଆଇଡି",
      ticketIdPlaceholder: "ଯେମିତି: JH-2026-0001",
      searchButton: "ଟ୍ରାକ୍ କରନ୍ତୁ",
      notFound: "ଏହି ଟିକେଟ୍ ଆଇଡି ସହିତ କୌଣସି ଅଭିଯୋଗ ମିଳିଲା ନାହିଁ। ଦୟାକରି ଯାଞ୍ଚ କରି ପୁନଃ ଚେଷ୍ଟା କରନ୍ତୁ।",
      invalidId: "ଦୟାକରି ଏକ ମାନ୍ୟ ଟିକେଟ୍ ଆଇଡି ଲେଖନ୍ତୁ।",
      backToSearch: "← ଅନ୍ୟ ଟିକେଟ୍ ଖୋଜନ୍ତୁ",
      statusHeading: "ଅଭିଯୋଗର ସ୍ଥିତି",
      problemLabel: "ସମସ୍ୟା",
      categoryLabel: "ବିଭାଗ",
      routedToLabel: "ପଠାଯାଇଛି",
      timelineHeading: "ପ୍ରଗତି",
      timeline: {
        submitted: "ଦାଖଲ ହେଲା",
        review: "ସମୀକ୍ଷାରେ ଅଛି",
        routed: "ପଠାଯାଇଛି",
        inProgress: "ଚାଲୁ ଅଛି",
        resolved: "ସମାଧାନ ହେଲା",
      },
      trackALabel: "ଟ୍ରାକ୍ A · ନଗର ନିଗମ",
      trackBLabel: "ଟ୍ରାକ୍ B · ଗବେଷଣା ଅନୁଷ୍ଠାନ",
      reportPhotoLabel: "ଆପଣ ଦାଖଲ କରିଥିବା ଫଟୋ",
      reportPhotoAlt: "ଏହି ଅଭିଯୋଗ ସହିତ ଦାଖଲ ହୋଇଥିବା ଫଟୋ",
      closurePhotoLabel: "ସମାଧାନ ଫଟୋ",
      closurePhotoAlt: "ସମସ୍ୟା ସମାଧାନ ହୋଇଥିବାର ପୁଷ୍ଟି କରୁଥିବା ଫଟୋ",
      institutionLabel: "ନିଯୁକ୍ତ ଅନୁଷ୍ଠାନ",
      matchStatusLabel: "ମେଳ ସ୍ଥିତି",
      proposalStatusLabel: "ପ୍ରସ୍ତାବ ସ୍ଥିତି",
      milestonesHeading: "ଗବେଷଣା ମାଇଲଖୁଣ୍ଟ",
      pilotVerdictLabel: "ପାଇଲଟ ଯାଞ୍ଚ",
    },
    transparency: {
      heading: "ସ୍ୱଚ୍ଛତା ଡ୍ୟାସବୋର୍ଡ",
      sub: "ଝାରଖଣ୍ଡ ସାରା ଅଭିଯୋଗ କିପରି ପରିଚାଳିତ ହେଉଛି ତାହାର ସାର୍ବଜନୀନ, ସଂକଳିତ ତଥ୍ୟ।",
      dataNote: "ସଂଖ୍ୟା ସମୟକ୍ରମେ ସଂକଳିତ ଏବଂ ଅପଡେଟ୍ ହୁଏ। କୌଣସି ବ୍ୟକ୍ତିଗତ ତଥ୍ୟ ଦେଖାଯାଏ ନାହିଁ।",
      statsHeading: "ସାରାଂଶ",
      statFiled: "ଦାଖଲ ହୋଇଥିବା ଅଭିଯୋଗ",
      statResolved: "ସମାଧାନ ହୋଇଥିବା ଅଭିଯୋଗ",
      statDistricts: "ଅନ୍ତର୍ଭୁକ୍ତ ଜିଲ୍ଲା",
      statInstitutions: "ଯୋଡ଼ି ହୋଇଥିବା ଅନୁଷ୍ଠାନ",
      districtHeading: "ଜିଲ୍ଲା ଅନୁସାରେ ଅଭିଯୋଗ",
      categoryHeading: "ବିଭାଗ ଅନୁସାରେ ଅଭିଯୋଗ",
      trackSplitHeading: "ଟ୍ରାକ୍ A ବନାମ ଟ୍ରାକ୍ B",
      trackSplitSub: "ନଗର ନିଗମ ବନାମ ଗବେଷଣା ଅନୁଷ୍ଠାନ ଦ୍ୱାରା ପରିଚାଳନା।",
      resolutionHeading: "ସମାଧାନର ପରିଣାମ",
      resolutionPassed: "ପ୍ରମାଣିତ ଭାବରେ ସମାଧାନ",
      resolutionFailed: "ପ୍ରମାଣୀକରଣ ବିଫଳ",
      resolutionPending: "ପ୍ରମାଣୀକରଣ ବାକି",
      demoNotice: "ନମୁନା ତଥ୍ୟ ଦେଖାଯାଉଛି — ଲାଇଭ୍ ସର୍ଭର ସହିତ ସମ୍ପର୍କ ହୋଇପାରିଲା ନାହିଁ।",
      moreDepthLink: "ବିଭାଗ/ଟ୍ରାକ୍-ସ୍ତରୀୟ ବିସ୍ତୃତ ବିବରଣୀ ଖୋଜୁଛନ୍ତି? ସମ୍ପୂର୍ଣ୍ଣ ସରକାରୀ ଡ୍ୟାସବୋର୍ଡ ଦେଖନ୍ତୁ।",
    },
    about: {
      heading: "ସହଯୋଗ ବିଷୟରେ",
      intro:
        "ସହଯୋଗ ଏକ ବହୁଭାଷୀ, AI-ସହାୟତାପ୍ରାପ୍ତ ପ୍ଲାଟଫର୍ମ ଯାହା ଝାରଖଣ୍ଡର ନାଗରିକମାନଙ୍କୁ ନାଗରିକ ସମସ୍ୟା ଜଣାଇବାରେ ସାହାଯ୍ୟ କରେ ଏବଂ ସରକାରକୁ ଅଧିକ ଶୀଘ୍ର ଓ ନ୍ୟାୟୋଚିତ ଭାବରେ ପ୍ରତିକ୍ରିୟା ଦେବାରେ ସକ୍ଷମ କରେ।",
      howHeading: "ଏହା କିପରି କାର୍ଯ୍ୟ କରେ",
      howIntro: "AI ସାହାଯ୍ୟ କରେ — ମନୁଷ୍ୟ ନିଷ୍ପତ୍ତି ନିଅନ୍ତି। ପ୍ରତ୍ୟେକ ପାହାଚରେ, ସ୍ୱୟଂଚାଳିତ ସହାୟତାକୁ କାର୍ଯ୍ୟାନୁଷ୍ଠାନ ପୂର୍ବରୁ ଏକ ବ୍ୟକ୍ତି ଯାଞ୍ଚ କରନ୍ତି।",
      step1Title: "୧. ଆପଣ ସମସ୍ୟାର ବର୍ଣ୍ଣନା କରନ୍ତି",
      step1Body:
        "ଆପଣଙ୍କ ନିଜ ଭାଷାରେ, ନିଜ ଶବ୍ଦରେ, ଟାଇପ୍ କରି କିମ୍ବା କହି। ଆମର ସିଷ୍ଟମ୍ ଏହାକୁ ପଢ଼େ କିମ୍ବା ଶୁଣେ ଏବଂ ବିଭାଗ ଓ ଗମ୍ଭୀରତାକୁ ସ୍ୱୟଂଚାଳିତ ଭାବରେ ନିର୍ଣ୍ଣୟ କରେ — ଆପଣଙ୍କୁ କେବେ ହେଲେ ନିଜେ ଏହାକୁ ବର୍ଗୀକରଣ କରିବାର ଆବଶ୍ୟକତା ନାହିଁ।",
      step2Title: "୨. ଆମେ ନକଲ ଯାଞ୍ଚ କରୁ",
      step2Body:
        "ଏକା ସମସ୍ୟା ପାଇଁ ଅନେକ ଟିକେଟ୍ ଏଡ଼ାଇବାକୁ ସିଷ୍ଟମ୍ ଆପଣଙ୍କ ଅଭିଯୋଗକୁ ସେହି ଅଞ୍ଚଳର ପୂର୍ବ ଅଭିଯୋଗ ସହିତ ତୁଳନା କରେ।",
      step3Title: "୩. ପ୍ରାଧାନ୍ୟ ନିର୍ଣ୍ଣୟ ହୁଏ",
      step3Body:
        "ଗମ୍ଭୀରତା, ସ୍ଥାନ ଏବଂ ବିଭାଗ ଆଧାରରେ ଅଭିଯୋଗକୁ ଏକ ପ୍ରାଧାନ୍ୟ ଦିଆଯାଏ ଯାହା ଦ୍ୱାରା ଜରୁରୀ ବିଷୟଗୁଡ଼ିକ ଧାଡ଼ିରେ ହଜିଯାଏ ନାହିଁ।",
      step4Title: "୪. ଏକ ମନୁଷ୍ୟ ସମୀକ୍ଷା କରନ୍ତି, ତାପରେ ପଠାଯାଏ",
      step4Body:
        "ଏକ ପ୍ରଶିକ୍ଷିତ ସମୀକ୍ଷକ ମୂଲ୍ୟାୟନ ଯାଞ୍ଚ କରନ୍ତି। ସାଧାରଣ ନାଗରିକ ସମସ୍ୟା ସ୍ଥାନୀୟ ନଗର ନିଗମ (ଟ୍ରାକ୍ A) କୁ ଯାଏ; ବଡ଼ କିମ୍ବା ଗବେଷଣା-ଉପଯୋଗୀ ସମସ୍ୟା ଏକ ସହଭାଗୀ ଶିକ୍ଷାନୁଷ୍ଠାନ କିମ୍ବା ଗବେଷଣା ଅନୁଷ୍ଠାନ (ଟ୍ରାକ୍ B) କୁ ପଠାଯାଇପାରେ।",
      contactHeading: "ପ୍ରଶ୍ନ କିମ୍ବା ମତାମତ?",
      contactBody: "ପୂର୍ବରୁ ଦାଖଲ ହୋଇଥିବା ଅଭିଯୋଗ ଯାଞ୍ଚ କରିବାକୁ 'ଆପଣଙ୍କ ଅଭିଯୋଗ ଟ୍ରାକ୍ କରନ୍ତୁ' ବ୍ୟବହାର କରନ୍ତୁ। ନୂଆ ନାଗରିକ ସମସ୍ୟା ରିପୋର୍ଟ କରିବାକୁ 'ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ' ବ୍ୟବହାର କରନ୍ତୁ।",
    },
  },

  ur: {
    common: {
      voiceOn: "آواز کے جوابات آن",
      voiceOff: "آواز کے جوابات آف",
      back: "پیچھے",
      next: "آگے",
      continue: "جاری رکھیں",
      submit: "جمع کریں",
      cancel: "منسوخ کریں",
      close: "بند کریں",
      loading: "لوڈ ہو رہا ہے...",
      retry: "دوبارہ کوشش کریں",
      optional: "اختیاری",
      required: "لازمی",
      yes: "جی ہاں",
      no: "نہیں",
      edit: "ترمیم کریں",
      search: "تلاش کریں",
      viewAll: "سب دیکھیں",
      learnMore: "مزید جانیں",
      errorGeneric: "کچھ غلط ہو گیا۔ براہ کرم دوبارہ کوشش کریں۔",
      networkError: "سرور سے رابطہ نہیں ہو سکا۔ براہ کرم اپنا کنکشن چیک کریں اور دوبارہ کوشش کریں۔",
      skipToContent: "مین مواد پر جائیں",
    },
    nav: {
      home: "ہوم",
      report: "مسئلہ درج کریں",
      track: "ٹریک کریں",
      transparency: "شفافیت",
      about: "تعارف",
      language: "زبان",
    },
    header: {
      brand: "سہیوگ",
      brandSub: "حکومتِ جھارکھنڈ · شکایت ازالہ پورٹل",
      operatorBadge: "ڈی این او آپریٹر پورٹل",
      institutionBadge: "ادارہ پورٹل",
      governmentBadge: "حکومتی ڈیش بورڈ",
    },
    footer: {
      about: "سہیوگ کے بارے میں",
      helpline: "ہیلپ لائن",
      helplineNumber: "1800-XXX-XXXX (ڈیمو)",
      privacy: "رازداری کی پالیسی",
      terms: "استعمال کی شرائط",
      disclaimer:
        "سہیوگ سمارٹ انڈیا ہیکاتھون 2026 کے لیے بنایا گیا ایک نمائشی پلیٹ فارم ہے۔ یہ ابھی حکومت کی لائیو سروس نہیں ہے۔",
      copyright: "© 2026 حکومتِ جھارکھنڈ۔ جمیع حقوق محفوظ ہیں۔",
    },
    home: {
      heroTitle: "سہیوگ",
      heroTagline: "آپ کی آواز سنی جائے گی، اور اس پر عمل ہوگا — ایک بہتر جھارکھنڈ کے لیے۔",
      heroSub:
        "اپنی زبان میں شہری مسائل کی شکایت درج کریں۔ ہمارا نظام ہر شکایت کی جانچ کرتا ہے، ترجیح طے کرتا ہے اور صحیح لوگوں تک پہنچاتا ہے — اور کوئی بھی کارروائی سے پہلے ہمیشہ ایک انسان جائزہ لیتا ہے۔",
      ctaPrimary: "مسئلہ درج کریں",
      ctaSecondary: "شکایت ٹریک کریں",
      statsHeading: "ایک نظر میں سہیوگ",
      statFiled: "درج شکایات",
      statResolved: "حل شدہ شکایات",
      statDistricts: "شامل ضلعے",
      statInstitutions: "شریک ادارے",
      feedHeading: "حالیہ عوامی شکایات",
      feedSubtitle: "جھارکھنڈ بھر میں درج شکایات کی ایک لائیو فہرست۔",
      filterStatus: "حالت",
      filterDistrict: "ضلع",
      filterAllStatuses: "تمام حالتیں",
      filterAllDistricts: "تمام ضلعے",
      feedEmpty: "ان فلٹرز سے میل کھاتی کوئی شکایت نہیں ملی۔",
      mapHeading: "مسائل کہاں رپورٹ ہو رہے ہیں",
      mapCaption: "حالیہ شکایات کے تخمینی مقامات (مثال کے طور پر)۔",
      demoBanner: "نمونہ ڈیٹا دکھایا جا رہا ہے — اس وقت لائیو سرور سے رابطہ نہیں ہو سکا۔",
    },
    status: {
      registered: "درج شدہ",
      in_progress: "جاری",
      resolved: "حل شدہ",
      escalated_track_b: "ٹریک B کو بھیجی گئی",
      merged: "موجودہ شکایت میں شامل",
    },
    submit: {
      wizardTitle: "مسئلہ درج کریں",
      stepOf: "مرحلہ {n} / 5",
      steps: {
        describe: "تفصیل",
        evidence: "ثبوت",
        location: "مقام",
        review: "جائزہ",
        done: "مکمل",
      },
      exitConfirm: "ابھی جانے سے یہ شکایت محفوظ نہیں ہوگی۔ جاری رکھیں؟",
      demoNotice:
        "شکایت سروس سے رابطہ نہیں ہو سکا — آپ ڈیمو موڈ میں آزما سکتے ہیں، لیکن کچھ بھی محفوظ نہیں ہوگا۔",

      describeHeading: "مسئلہ کیا ہے؟",
      describeSub: "اپنے الفاظ میں بتائیں — لکھ کر یا بول کر۔ کوئی زمرہ منتخب کرنے کی ضرورت نہیں، ہمارا نظام خود یہ سمجھ لیتا ہے۔",
      textLabel: "مسئلے کی تفصیل بتائیں",
      textPlaceholder: "مثلاً: بازار کے قریب مین روڈ پر ایک بڑا گڑھا ہے...",
      textHelp: "جو زبان آپ کے لیے آسان ہو، اسی میں لکھیں۔",
      orDivider: "یا",
      voiceLabel: "اس کے بجائے ریکارڈ کریں",
      voiceStart: "ریکارڈنگ شروع کریں",
      voiceStop: "ریکارڈنگ روکیں",
      voiceRecording: "ریکارڈ ہو رہا ہے...",
      voiceRecorded: "ریکارڈنگ مکمل ہو گئی",
      voiceUploading: "آپ کی ریکارڈنگ اپلوڈ ہو رہی ہے...",
      voiceUploadFailed: "ریکارڈنگ اپلوڈ نہیں ہو سکی۔ براہ کرم لکھ کر آزمائیں۔",
      voiceUnsupported: "اس براؤزر میں وائس ریکارڈنگ معاون نہیں ہے۔",
      transcribing: "آپ کی ریکارڈنگ تحریر کی جا رہی ہے...",
      transcribedLabel: "ہم نے یہ سنا:",
      analyzing: "آپ کی تفصیل پڑھی جا رہی ہے...",
      understoodHeading: "ہم نے یہ سمجھا",
      understoodDomain: "AI سے شناخت شدہ زمرہ",
      understoodSeverity: "AI سے شناخت شدہ شدت",
      understoodEdit: "یہ درست نہیں ہے",
      understoodConfirm: "جی ہاں، یہ درست ہے",
      correctionLabel: "ہمیں بتائیں کہاں غلطی ہوئی",
      correctionPlaceholder: "یہاں تفصیل درست کریں...",
      correctionSave: "تصحیح محفوظ کریں",
      validationNeedText: "براہ کرم مسئلے کی تفصیل لکھیں یا ایک وائس نوٹ ریکارڈ کریں۔",
      describeSubmit: "جمع کریں →",

      evidenceHeading: "ایک تصویر شامل کریں",
      evidenceSub: "ایک واضح تصویر ہماری ٹیم کو شکایت کی تصدیق کرنے اور تیزی سے کارروائی کرنے میں مدد دیتی ہے۔",
      evidenceCameraOption: "ابھی تصویر لیں",
      evidenceUploadOption: "گیلری سے اپلوڈ کریں",
      uploadLabel: "ایک تصویر منتخب کریں",
      uploadHint: "JPG یا PNG، مسئلے کی جگہ پر لی گئی۔",
      uploadButton: "تصویر اپلوڈ کریں →",
      uploadedAlt: "اپلوڈ کی گئی ثبوت تصویر",
      removePhoto: "تصویر ہٹائیں",
      photoAnalyzing: "آپ کی تصویر جانچی جا رہی ہے...",
      photoRequired: "جاری رکھنے کے لیے براہ کرم ایک تصویر شامل کریں۔",
      matchWarningHeading: "یہ ایک موجودہ شکایت جیسی لگتی ہے",
      matchWarningBody:
        "ہمیں ایک ایسی شکایت ملی ہے جو ممکنہ طور پر اس مسئلے کا احاطہ پہلے ہی کر رہی ہے۔ آپ پھر بھی جاری رکھ سکتے ہیں، یا واپس جا کر دیکھ سکتے ہیں۔",
      continueAnyway: "پھر بھی جاری رکھیں",
      tryDifferentPhoto: "دوسری تصویر آزمائیں",
      cameraStart: "کیمرہ شروع کریں",
      cameraCapture: "تصویر لیں",
      cameraRetake: "دوبارہ لیں",
      cameraUsePhoto: "یہ تصویر استعمال کریں",
      cameraDenied: "کیمرہ دستیاب نہیں ہو سکا۔ براہ کرم گیلری سے تصویر اپلوڈ کریں۔",
      cameraStarting: "کیمرہ شروع ہو رہا ہے...",

      locationHeading: "یہ کہاں ہو رہا ہے؟",
      locationSub: "اپنا موجودہ مقام استعمال کریں، یا پتہ خود لکھیں۔",
      gpsButton: "میرا موجودہ مقام استعمال کریں",
      gpsDetecting: "آپ کا مقام معلوم کیا جا رہا ہے...",
      gpsSuccess: "مقام حاصل ہو گیا",
      gpsFailed: "آپ کا مقام معلوم نہیں ہو سکا۔ براہ کرم نیچے پتہ لکھیں۔",
      gpsUnsupported: "اس براؤزر میں لوکیشن سروس دستیاب نہیں ہے۔",
      addressLabel: "پتہ / نشانی",
      addressPlaceholder: "مثلاً: رانچی بس اسٹینڈ کے قریب، مین روڈ",
      districtLabel: "ضلع",
      districtPlaceholder: "اپنا ضلع منتخب کریں",
      locationButton: "مقام کی تصدیق کریں →",
      locationRequired: "براہ کرم مقام شیئر کریں یا پتہ لکھیں۔",

      reviewHeading: "اپنی شکایت کا جائزہ لیں",
      reviewSub: "جمع کرنے سے پہلے براہ کرم تفصیلات چیک کریں۔",
      reviewProblem: "مسئلہ",
      reviewCategory: "AI سے شناخت شدہ زمرہ",
      reviewPhoto: "تصویر",
      reviewLocation: "مقام",
      reviewDistrict: "ضلع",
      reviewEditStep: "ترمیم کریں",
      submitButton: "✓ شکایت جمع کریں",
      submitting: "آپ کی شکایت جمع کی جا رہی ہے...",
      submitFailed: "شکایت جمع نہیں ہو سکی۔ براہ کرم دوبارہ کوشش کریں۔",

      doneHeading: "شکایت جمع ہو گئی",
      ticketIdLabel: "آپ کی ٹکٹ آئی ڈی",
      trackButton: "اس شکایت کو ٹریک کریں",
      newReportButton: "ایک اور مسئلہ درج کریں",
      whatNextHeading: "اب کیا ہوگا؟",
      whatNextDedup: "ہمارا نظام جانچتا ہے کہ یہ کسی موجودہ شکایت کی نقل تو نہیں ہے۔",
      whatNextPriority: "اسے خودکار طور پر جانچا جاتا ہے اور ایک ترجیح دی جاتی ہے۔",
      whatNextHuman: "کچھ حتمی ہونے سے پہلے ایک انسانی جائزہ کار اس تجزیے کی جانچ کرتا ہے۔",
      whatNextRoute:
        "اسے یا تو آپ کے مقامی میونسپل ادارے (ٹریک A) کو بھیجا جاتا ہے، یا بڑے تحقیقی مسائل کے لیے کسی شریک ادارے (ٹریک B) کو بھیجا جاتا ہے۔",
    },
    track: {
      searchHeading: "اپنی شکایت ٹریک کریں",
      searchSub: "شکایت درج کرتے وقت ملنے والی ٹکٹ آئی ڈی درج کریں۔",
      ticketIdLabel: "ٹکٹ آئی ڈی",
      ticketIdPlaceholder: "مثلاً: JH-2026-0001",
      searchButton: "ٹریک کریں",
      notFound: "اس ٹکٹ آئی ڈی سے کوئی شکایت نہیں ملی۔ براہ کرم چیک کر کے دوبارہ کوشش کریں۔",
      invalidId: "براہ کرم ایک درست ٹکٹ آئی ڈی درج کریں۔",
      backToSearch: "← دوسری ٹکٹ تلاش کریں",
      statusHeading: "شکایت کی حالت",
      problemLabel: "مسئلہ",
      categoryLabel: "زمرہ",
      routedToLabel: "بھیجی گئی",
      timelineHeading: "پیش رفت",
      timeline: {
        submitted: "جمع ہوئی",
        review: "زیر جائزہ",
        routed: "بھیجی گئی",
        inProgress: "جاری",
        resolved: "حل شدہ",
      },
      trackALabel: "ٹریک A · میونسپل ادارہ",
      trackBLabel: "ٹریک B · تحقیقی ادارہ",
      reportPhotoLabel: "آپ کی بھیجی گئی تصویر",
      reportPhotoAlt: "اس شکایت کے ساتھ بھیجی گئی تصویر",
      closurePhotoLabel: "حل کی تصویر",
      closurePhotoAlt: "مسئلہ حل ہونے کی تصدیق کرنے والی تصویر",
      institutionLabel: "تفویض شدہ ادارہ",
      matchStatusLabel: "میچ کی صورتحال",
      proposalStatusLabel: "تجویز کی صورتحال",
      milestonesHeading: "تحقیقی سنگ میل",
      pilotVerdictLabel: "پائلٹ تصدیق",
    },
    transparency: {
      heading: "شفافیت ڈیش بورڈ",
      sub: "جھارکھنڈ بھر میں شکایات کس طرح نمٹائی جاتی ہیں اس کا عوامی، مجموعی ڈیٹا۔",
      dataNote: "اعداد و شمار وقتاً فوقتاً جمع اور اپڈیٹ کیے جاتے ہیں۔ کوئی ذاتی ڈیٹا نہیں دکھایا جاتا۔",
      statsHeading: "جائزہ",
      statFiled: "درج شکایات",
      statResolved: "حل شدہ شکایات",
      statDistricts: "شامل ضلعے",
      statInstitutions: "شریک ادارے",
      districtHeading: "ضلع کے لحاظ سے شکایات",
      categoryHeading: "زمرے کے لحاظ سے شکایات",
      trackSplitHeading: "ٹریک A بمقابلہ ٹریک B",
      trackSplitSub: "میونسپل بمقابلہ تحقیقی ادارے کے ذریعے نمٹانا۔",
      resolutionHeading: "حل کے نتائج",
      resolutionPassed: "تصدیق شدہ حل",
      resolutionFailed: "تصدیق ناکام",
      resolutionPending: "تصدیق زیر التوا",
      demoNotice: "نمونہ ڈیٹا دکھایا جا رہا ہے — لائیو سرور سے رابطہ نہیں ہو سکا۔",
      moreDepthLink: "محکمہ/ٹریک کی سطح کی مزید تفصیل چاہیے؟ مکمل حکومتی ڈیش بورڈ دیکھیں۔",
    },
    about: {
      heading: "سہیوگ کے بارے میں",
      intro:
        "سہیوگ ایک کثیرلسانی، AI کی مدد یافتہ پلیٹ فارم ہے جو جھارکھنڈ کے شہریوں کو شہری مسائل کی شکایت درج کرنے میں مدد دیتا ہے اور حکومت کو تیزی اور انصاف کے ساتھ جواب دینے کے قابل بناتا ہے۔",
      howHeading: "یہ کیسے کام کرتا ہے",
      howIntro: "AI مدد کرتا ہے — فیصلہ انسان کرتا ہے۔ ہر مرحلے پر، خودکار مدد کو کارروائی سے پہلے ایک انسان کے ذریعے جانچا جاتا ہے۔",
      step1Title: "1۔ آپ مسئلے کی وضاحت کرتے ہیں",
      step1Body:
        "اپنے الفاظ میں، اپنی زبان میں، لکھ کر یا بول کر۔ ہمارا نظام اسے پڑھتا یا سنتا ہے اور زمرہ اور شدت خود بخود طے کرتا ہے — آپ کو کبھی خود اسے درجہ بندی کرنے کی ضرورت نہیں۔",
      step2Title: "2۔ ہم نقل کی جانچ کرتے ہیں",
      step2Body:
        "ایک ہی مسئلے کے لیے متعدد ٹکٹ بننے سے بچنے کے لیے نظام آپ کی شکایت کا اسی علاقے کی موجودہ شکایات سے موازنہ کرتا ہے۔",
      step3Title: "3۔ ترجیح طے کی جاتی ہے",
      step3Body:
        "شدت، مقام اور زمرے کی بنیاد پر شکایت کو ایک ترجیح دی جاتی ہے تاکہ ضروری معاملات قطار میں کھو نہ جائیں۔",
      step4Title: "4۔ ایک انسان جائزہ لیتا ہے، پھر بھیجی جاتی ہے",
      step4Body:
        "ایک تربیت یافتہ جائزہ کار تجزیے کی جانچ کرتا ہے۔ معمول کے شہری مسائل مقامی میونسپل ادارے (ٹریک A) کو جاتے ہیں؛ بڑے یا تحقیقی لائق مسائل کسی شریک تعلیمی یا تحقیقی ادارے (ٹریک B) کو بھیجے جا سکتے ہیں۔",
      contactHeading: "سوالات یا رائے؟",
      contactBody: "پہلے سے درج شکایت چیک کرنے کے لیے 'اپنی شکایت ٹریک کریں' استعمال کریں۔ نئے شہری مسئلے کی اطلاع دینے کے لیے 'شکایت درج کریں' استعمال کریں۔",
    },
  },

  // Santali (Ol Chiki script) - interface text only. First-draft
  // AI-assisted translation, not yet checked by a fluent Santali speaker -
  // see this file's header comment for why voice input/AI translation
  // aren't available in this language regardless of what this block says.
  sat: {
    common: {
      back: "ᱛᱟᱭᱚᱢ",
      next: "ᱟᱭᱚᱢ",
      continue: "ᱞᱟᱦᱟ ᱛᱟᱦᱮᱸᱱᱟ",
      submit: "ᱡᱟᱴᱟᱣ",
      cancel: "ᱵᱟᱛᱤᱞ",
      close: "ᱵᱚᱸᱫᱚᱭ",
      loading: "ᱞᱟᱫᱮ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ...",
      retry: "ᱫᱳᱵᱟᱨ ᱠᱩᱭᱟᱹ ᱧᱮᱞ ᱢᱮ",
      optional: "ᱵᱟᱪᱷᱟᱣ ᱫᱟᱲᱮᱭᱟᱜ",
      required: "ᱡᱟᱹᱨᱩᱨᱤ",
      yes: "ᱦᱚᱭ",
      no: "ᱵᱟᱭ",
      edit: "ᱥᱟᱯᱲᱟᱣ",
      search: "ᱛᱟᱲᱟᱥ",
      viewAll: "ᱡᱚᱛᱚ ᱧᱮᱞ ᱢᱮ",
      learnMore: "ᱟᱨᱦᱚᱸ ᱵᱟᱰᱟᱭ ᱢᱮ",
      errorGeneric: "ᱢᱤᱫ ᱛᱮᱦᱮᱸᱱ ᱟᱱᱟᱴ ᱦᱩᱭᱮᱱᱟ। ᱫᱚᱵᱟᱨ ᱠᱩᱨᱩᱢᱩᱴᱩ ᱠᱟᱛᱮ ᱧᱮᱞ ᱢᱮ।",
      networkError: "ᱥᱚᱨᱵᱷᱟᱨ ᱛᱟᱲᱟᱨ ᱦᱩᱭ ᱵᱟᱭ ᱫᱟᱲᱮᱭᱟᱜᱼᱟᱱᱟ। ᱟᱢᱟᱜ ᱤᱱᱴᱚᱨᱱᱮᱴ ᱥᱟᱸᱵᱟᱫ ᱧᱮᱞ ᱠᱟᱛᱮ ᱫᱚᱵᱟᱨ ᱠᱩᱨᱩᱢᱩᱴᱩ ᱢᱮ।",
      skipToContent: "ᱢᱩᱬᱩᱛ ᱡᱤᱱᱤᱥ ᱛᱮ ᱛᱮᱦᱮᱸᱱ ᱢᱮ",
      all: "ᱡᱚᱛᱚ",
    },
    nav: {
      home: "ᱚᱲᱟᱜ ᱥᱟᱦᱴᱟ",
      report: "ᱡᱟᱶ ᱨᱤᱯᱳᱴ ᱢᱮ",
      track: "ᱴᱨᱮᱠ",
      transparency: "ᱯᱟᱨᱥᱤᱭᱟᱹᱛᱟᱹ",
      about: "ᱵᱟᱵᱚᱛ",
      language: "ᱨᱚᱲ",
    },
    header: {
      brand: "ᱥᱟᱦᱭᱳᱜ",
      brandSub: "ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱥᱚᱨᱠᱟᱨ · ᱟᱨᱡᱤ ᱥᱩᱞᱟᱹᱭ ᱯᱳᱴᱟᱞ",
      operatorBadge: "ᱰᱤᱮᱱᱳ ᱳᱯᱚᱨᱮᱴᱚᱨ ᱯᱳᱴᱟᱞ",
      institutionBadge: "ᱥᱚᱸᱥᱛᱷᱟ ᱯᱳᱴᱟᱞ",
      governmentBadge: "ᱥᱚᱨᱠᱟᱨ ᱰᱮᱥᱵᱳᱨᱰ",
    },
    footer: {
      about: "ᱥᱟᱦᱭᱳᱜ ᱵᱟᱵᱚᱛ",
      helpline: "ᱦᱮᱞᱯᱞᱟᱭᱤᱱ",
      helplineNumber: "1800-XXX-XXXX (ᱰᱮᱢᱳ)",
      privacy: "ᱞᱩᱠᱩᱛᱤ ᱱᱤᱭᱚᱢ",
      terms: "ᱵᱮᱵᱚᱦᱟᱨ ᱱᱤᱭᱚᱢ",
      disclaimer:
        "ᱥᱟᱦᱭᱳᱜ ᱲᱟᱶ Smart India Hackathon 2026 ᱞᱟᱹᱜᱤᱫ ᱛᱮᱭᱟᱨ ᱠᱟᱱ ᱢᱤᱫ ᱰᱮᱢᱳᱱᱥᱴᱨᱮᱥᱟᱱ ᱯᱞᱮᱴᱯᱷᱚᱨᱚᱢ ᱠᱟᱱᱟ। ᱱᱚᱶᱟ ᱚᱠᱛᱚ ᱡᱤᱣᱚᱱ ᱥᱚᱨᱠᱟᱨᱤ ᱥᱮᱵᱟ ᱵᱟᱭ ᱠᱟᱱᱟ।",
      copyright: "© 2026 ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱥᱚᱨᱠᱟᱨ। ᱡᱚᱛᱚ ᱦᱟᱠ ᱨᱮᱭᱟᱜ ᱦᱟᱛᱟᱸᱣ ᱠᱟᱱᱟ।",
    },
    home: {
      heroTitle: "ᱥᱟᱦᱭᱳᱜ",
      heroTagline: "ᱟᱢᱟᱜ ᱨᱚᱲ, ᱟᱭᱩᱢ ᱠᱟᱛᱮ ᱠᱟᱹᱢᱤ ᱦᱩᱭᱩᱜᱼᱟ — ᱵᱮᱥ ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱞᱟᱹᱜᱤᱫ।",
      heroSub:
        "ᱟᱢᱟᱜ ᱯᱟᱹᱨᱥᱤ ᱛᱮ ᱦᱚᱲ ᱠᱚᱣᱟᱜ ᱞᱟᱹᱞᱤᱥ ᱠᱚ ᱵᱚᱨᱱᱚᱱ ᱢᱮ। ᱟᱢᱨᱮᱱ ᱵᱚᱱᱫᱮᱡ ᱥᱟᱱᱟᱢ ᱞᱟᱹᱞᱤᱥ ᱠᱚ ᱵᱤᱰᱟᱹᱣ, ᱮᱛᱚᱦᱚᱵ ᱟᱨ ᱥᱚᱨᱟᱥᱚᱨᱤ ᱦᱚᱲ ᱠᱚ ᱴᱷᱮᱱ ᱩᱯᱟᱹᱭ ᱮᱢᱟ — ᱟᱨ ᱠᱟᱹᱢᱤ ᱦᱟᱛᱟᱣ ᱞᱟᱦᱟᱨᱮ ᱢᱤᱫ ᱦᱚᱲ ᱡᱚᱛᱚ ᱚᱠᱛᱮ ᱵᱤᱰᱟᱹᱣ ᱮ ᱠᱚᱨᱟᱣᱼᱟ।",
      ctaPrimary: "ᱡᱟᱶ ᱨᱤᱯᱳᱴ ᱢᱮ",
      ctaSecondary: "ᱟᱨᱡᱤ ᱴᱨᱮᱠ ᱢᱮ",
      statsHeading: "ᱥᱟᱦᱭᱳᱜ ᱢᱤᱫ ᱧᱮᱞ ᱨᱮ",
      statFiled: "ᱡᱟᱶ ᱟᱨᱡᱤ ᱠᱚ",
      statResolved: "ᱴᱷᱤᱠ ᱦᱩᱭ ᱞᱮᱱ ᱟᱨᱡᱤ ᱠᱚ",
      statDistricts: "ᱛᱟᱦᱮᱸᱱ ᱡᱤᱞᱟ ᱠᱚ",
      statInstitutions: "ᱡᱩᱲᱟᱶ ᱠᱟᱱ ᱥᱚᱸᱥᱛᱷᱟ ᱠᱚ",
      feedHeading: "ᱱᱤᱛᱚᱜ ᱡᱟᱶ ᱟᱨᱡᱤ ᱠᱚ",
      feedSubtitle: "ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱨᱮᱭᱟᱜ ᱟᱨᱡᱤ ᱠᱚᱨᱮᱭᱟᱜ ᱡᱤᱣᱚᱱ ᱯᱷᱤᱰ।",
      filterStatus: "ᱠᱟᱹᱢᱤ ᱚᱠᱛᱚ",
      filterDistrict: "ᱡᱤᱞᱟ",
      filterAllStatuses: "ᱡᱚᱛᱚ ᱠᱟᱹᱢᱤ ᱚᱠᱛᱚ",
      filterAllDistricts: "ᱡᱚᱛᱚ ᱡᱤᱞᱟ",
      feedEmpty: "ᱱᱚᱶᱟ ᱪᱷᱟᱸᱴ ᱛᱮ ᱢᱤᱫᱴᱟᱝ ᱟᱨᱡᱤ ᱵᱟᱭ ᱢᱮᱴᱟᱣᱮᱱᱟ।",
      mapHeading: "ᱟᱨᱡᱤ ᱠᱚ ᱚᱠᱟ ᱛᱮ ᱡᱟᱶ ᱦᱩᱭᱩᱜᱼᱟᱠᱟᱱᱟ",
      mapCaption: "ᱱᱟᱦᱟᱜ ᱟᱨᱡᱤ ᱠᱚᱨᱮᱭᱟᱜ ᱚᱱᱢᱟᱱ ᱴᱷᱟᱶ (ᱪᱤᱛᱟᱹᱨ ᱞᱟᱹᱜᱤᱫ)।",
      demoBanner: "ᱰᱮᱢᱳ ᱰᱟᱴᱟ ᱫᱮᱠᱷᱟᱣᱠᱟᱱᱟ — ᱱᱤᱛᱚᱜ ᱵᱮᱠᱮᱸᱰ ᱛᱟᱲᱟᱨ ᱦᱩᱭ ᱵᱟᱭ ᱫᱟᱲᱮᱭᱟᱜᱼᱟᱱᱟ।",
    },
    status: {
      registered: "ᱚᱞ ᱦᱩᱭ ᱞᱮᱱᱟ",
      in_progress: "ᱠᱟᱹᱢᱤ ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟ",
      resolved: "ᱴᱷᱤᱠ ᱦᱩᱭᱮᱱᱟ",
      escalated_track_b: "ᱴᱨᱮᱠ B ᱛᱮ ᱠᱩᱞ ᱦᱩᱭᱮᱱᱟ",
      merged: "ᱢᱮᱲᱟᱣ ᱟᱨᱡᱤ ᱥᱟᱶ ᱡᱩᱲᱟᱣ ᱦᱩᱭᱮᱱᱟ",
    },
    submit: {
      wizardTitle: "ᱡᱟᱶ ᱨᱤᱯᱳᱴ ᱢᱮ",
      stepOf: "5 ᱨᱮ {n} ᱟᱹᱭᱫᱟᱹ",
      steps: {
        describe: "ᱵᱟᱰᱟᱭ",
        evidence: "ᱥᱟᱠᱷᱭᱟᱹᱫ",
        location: "ᱡᱟᱭᱜᱟ",
        review: "ᱧᱮᱞ ᱫᱚᱦᱚ",
        done: "ᱡᱟᱴᱟᱣ ᱦᱩᱭᱮᱱᱟ",
      },
      exitConfirm: "ᱱᱤᱛᱚᱜ ᱵᱟᱦᱨᱮ ᱚᱰᱚᱠᱠᱮᱫ ᱱᱚᱶᱟ ᱨᱤᱯᱳᱴ ᱵᱟᱛᱤᱞ ᱦᱩᱭ ᱡᱟᱶᱟ। ᱞᱟᱦᱟ ᱛᱟᱦᱮᱸᱱᱟᱢᱟ ᱪᱮᱫ?",
      demoNotice:
        "ᱨᱤᱯᱳᱴᱤᱝ ᱥᱮᱵᱟ ᱛᱟᱲᱟᱨ ᱦᱩᱭ ᱵᱟᱭ ᱫᱟᱲᱮᱭᱟᱜᱼᱟᱱᱟ — ᱟᱢ ᱰᱮᱢᱳ ᱨᱮ ᱠᱩᱭᱟᱹ ᱫᱟᱲᱮᱭᱟᱜ ᱫᱟᱲᱮᱭᱟᱜ, ᱢᱮᱱᱠᱷᱟᱱ ᱚᱠᱟ ᱦᱮᱸ ᱡᱚᱢᱟᱭ ᱵᱟᱭ ᱛᱟᱦᱮᱸᱱᱟ।",

      describeHeading: "ᱟᱱᱟᱴ ᱫᱚ ᱪᱮᱫ?",
      describeSub: "ᱚᱞ ᱠᱟᱛᱮ ᱟᱨ ᱠᱟᱛᱷᱟ ᱠᱟᱛᱮ, ᱟᱢᱟᱜ ᱚᱲᱟᱜ ᱠᱟᱛᱷᱟ ᱛᱮ ᱵᱟᱰᱟᱭ ᱢᱮ। ᱵᱟᱛᱟᱣ ᱦᱩᱰᱤᱧ ᱡᱟᱹᱨᱩᱨᱤ ᱠᱚᱸ, ᱟᱞᱮᱭᱟᱜ ᱥᱤᱥᱴᱚᱢ ᱚᱱᱟ ᱠᱟᱹᱢᱤ ᱟᱢ ᱞᱟᱹᱜᱤᱫ ᱛᱮ ᱦᱚᱨᱟᱜᱟ।",
      textLabel: "ᱟᱱᱟᱴ ᱨᱮᱭᱟᱜ ᱵᱚᱨᱱᱚᱱ ᱢᱮ",
      textPlaceholder: "ᱫᱟᱹᱭᱠᱟᱹ ᱞᱮᱠᱟᱛᱮ: ᱵᱟᱡᱟᱨ ᱥᱳᱨ ᱨᱮ ᱢᱩᱲᱩᱫ ᱰᱟᱦᱟᱨ ᱨᱮ ᱢᱤᱫᱴᱟᱝ ᱢᱟᱨᱟᱝ ᱜᱷᱚᱴ ᱢᱮᱱᱟᱜᱼᱟ...",
      textHelp: "ᱡᱟᱦᱟᱸ ᱨᱚᱲ ᱨᱮ ᱟᱢᱟᱜ ᱥᱩᱠᱩ ᱞᱮᱠᱟᱜ ᱚᱱᱟ ᱨᱚᱲ ᱛᱮ ᱚᱞ ᱢᱮ।",
      orDivider: "ᱟᱨᱠᱷᱟᱱ",
      voiceLabel: "ᱠᱟᱛᱷᱟ ᱨᱮᱠᱚᱰᱚᱨ ᱢᱮ",
      voiceStart: "ᱨᱮᱠᱚᱰᱤᱝ ᱮᱛᱟᱣ ᱢᱮ",
      voiceStop: "ᱨᱮᱠᱚᱰᱤᱝ ᱛᱟᱹᱡᱮᱢ ᱢᱮ",
      voiceRecording: "ᱨᱮᱠᱚᱰ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ...",
      voiceRecorded: "ᱨᱮᱠᱚᱰ ᱦᱩᱭᱮᱱᱟ",
      voiceUploading: "ᱟᱢᱟᱜ ᱨᱮᱠᱚᱰᱤᱝ ᱟᱯᱞᱳᱰ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ...",
      voiceUploadFailed: "ᱨᱮᱠᱚᱰᱤᱝ ᱟᱯᱞᱳᱰ ᱵᱟᱭ ᱫᱟᱲᱮᱭᱟᱜᱼᱟᱱᱟ। ᱫᱟᱭᱟ ᱠᱟᱛᱮ ᱚᱞ ᱠᱟᱛᱮ ᱠᱩᱭᱟᱹ ᱧᱮᱞ ᱢᱮ।",
      voiceUnsupported: "ᱱᱚᱶᱟ ᱵᱽᱨᱟᱣᱡᱚᱨ ᱨᱮ ᱠᱟᱛᱷᱟ ᱨᱮᱠᱚᱰᱤᱝ ᱵᱟᱭ ᱫᱟᱲᱮᱭᱟᱜᱼᱟᱱᱟ।",
      transcribing: "ᱟᱢᱟᱜ ᱨᱮᱠᱚᱰᱤᱝ ᱚᱞ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ...",
      transcribedLabel: "ᱟᱞᱮ ᱟᱭᱩᱢ ᱞᱮᱱᱟ:",
      analyzing: "ᱟᱢᱟᱜ ᱵᱟᱰᱟᱭ ᱯᱟᱰᱷᱟᱶ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ...",
      understoodHeading: "ᱱᱚᱶᱟ ᱟᱞᱮ ᱵᱟᱰᱟᱭ ᱮᱢᱟ",
      understoodDomain: "AI ᱧᱟᱢ ᱠᱟᱛᱮ ᱴᱷᱟᱹᱣᱠᱟ ᱠᱟᱴᱮᱜᱚᱨᱤ",
      understoodSeverity: "AI ᱧᱟᱢ ᱠᱟᱛᱮ ᱢᱟᱨᱟᱝ ᱨᱚᱠᱚᱢ",
      understoodEdit: "ᱱᱚᱶᱟ ᱴᱷᱤᱠ ᱵᱟᱝᱠᱟᱱᱟ",
      understoodConfirm: "ᱦᱚᱭ, ᱱᱚᱶᱟ ᱴᱷᱤᱠᱠᱟᱱᱟ",
      correctionLabel: "ᱟᱞᱮ ᱪᱮᱫ ᱜᱟᱞᱛᱤ ᱠᱟᱛᱮ ᱵᱩᱡᱷᱟᱹᱣ ᱞᱮᱫ ᱚᱱᱟ ᱵᱟᱰᱟᱭ ᱢᱮ",
      correctionPlaceholder: "ᱱᱚᱰᱮ ᱵᱟᱰᱟᱭ ᱴᱷᱤᱠ ᱢᱮ...",
      correctionSave: "ᱥᱟᱯᱲᱟᱣ ᱥᱟᱶᱨᱟᱠᱷᱚᱸ ᱢᱮ",
      validationNeedText: "ᱫᱟᱭᱟ ᱠᱟᱛᱮ ᱟᱱᱟᱴ ᱵᱟᱰᱟᱭ ᱢᱮ ᱟᱨ ᱠᱟᱛᱷᱟ ᱨᱮᱠᱚᱰ ᱢᱮ।",
      describeSubmit: "ᱡᱟᱴᱟᱣ ᱢᱮ →",

      evidenceHeading: "ᱢᱤᱫ ᱯᱷᱚᱴᱳ ᱡᱟᱴᱟᱣ ᱢᱮ",
      evidenceSub: "ᱢᱤᱫ ᱯᱷᱚᱴᱳ ᱛᱮ ᱟᱞᱮᱭᱟᱜ ᱴᱤᱢ ᱡᱚᱲᱟᱣ ᱠᱟᱛᱮ ᱟᱨᱡᱤ ᱛᱟᱲᱟᱨ ᱛᱮ ᱴᱷᱤᱠ ᱠᱟᱹᱢᱤ ᱫᱟᱲᱮᱭᱟᱜᱼᱟ।",
      evidenceCameraOption: "ᱱᱤᱛᱚᱜ ᱯᱷᱚᱴᱳ ᱩᱰᱩᱜ ᱢᱮ",
      evidenceUploadOption: "ᱜᱮᱞᱟᱨᱤ ᱠᱷᱚᱱ ᱟᱯᱞᱳᱰ ᱢᱮ",
      uploadLabel: "ᱢᱤᱫ ᱯᱷᱚᱴᱳ ᱵᱟᱪᱷᱟᱣ ᱢᱮ",
      uploadHint: "JPG ᱟᱨᱠᱷᱟᱱ PNG, ᱟᱱᱟᱴ ᱡᱟᱭᱜᱟ ᱨᱮ ᱩᱰᱩᱜ ᱠᱟᱱ।",
      uploadButton: "ᱯᱷᱚᱴᱳ ᱟᱯᱞᱳᱰ ᱢᱮ →",
      uploadedAlt: "ᱟᱯᱞᱳᱰ ᱠᱟᱱ ᱥᱟᱠᱷᱭᱟᱹᱫ ᱯᱷᱚᱴᱳ",
      removePhoto: "ᱯᱷᱚᱴᱳ ᱚᱰᱚᱠ ᱢᱮ",
      photoAnalyzing: "ᱟᱢᱟᱜ ᱯᱷᱚᱴᱳ ᱧᱮᱞ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ...",
      photoRequired: "ᱞᱟᱦᱟ ᱛᱟᱦᱮᱸᱱ ᱞᱟᱹᱜᱤᱫ ᱫᱟᱭᱟ ᱠᱟᱛᱮ ᱯᱷᱚᱴᱳ ᱡᱚᱲᱟᱣ ᱢᱮ।",
      matchWarningHeading: "ᱱᱚᱶᱟ ᱢᱤᱫ ᱛᱮᱦᱮᱸᱱ ᱟᱨᱡᱤ ᱞᱮᱠᱟ ᱧᱮᱞᱚᱜᱼᱟ",
      matchWarningBody:
        "ᱟᱞᱮ ᱢᱤᱫ ᱟᱨᱡᱤ ᱧᱟᱢ ᱞᱮᱱᱟ ᱡᱟᱦᱟᱸ ᱱᱚᱶᱟ ᱟᱱᱟᱴ ᱥᱟᱶ ᱡᱩᱲᱟᱶ ᱫᱟᱲᱮᱭᱟᱜᱼᱟ। ᱟᱢ ᱞᱟᱦᱟ ᱛᱟᱦᱮᱸᱱ ᱫᱟᱲᱮᱭᱟᱜ, ᱟᱨᱠᱷᱟᱱ ᱛᱟᱭᱚᱢ ᱠᱟᱛᱮ ᱧᱮᱞ ᱢᱮ।",
      continueAnyway: "ᱛᱟᱵᱮ ᱦᱮᱸ ᱞᱟᱦᱟ ᱛᱟᱦᱮᱸᱱ ᱢᱮ",
      tryDifferentPhoto: "ᱮᱴᱟᱜ ᱯᱷᱚᱴᱳ ᱧᱮᱞ ᱢᱮ",
      cameraStart: "ᱠᱮᱢᱮᱨᱟ ᱮᱛᱟᱣ ᱢᱮ",
      cameraCapture: "ᱩᱰᱩᱜ ᱢᱮ",
      cameraRetake: "ᱫᱳᱵᱟᱨ ᱩᱰᱩᱜ ᱢᱮ",
      cameraUsePhoto: "ᱱᱚᱶᱟ ᱯᱷᱚᱴᱳ ᱵᱮᱵᱚᱦᱟᱨ ᱢᱮ",
      cameraDenied: "ᱠᱮᱢᱮᱨᱟ ᱵᱟᱭ ᱧᱟᱢᱮᱱᱟ। ᱫᱟᱭᱟ ᱠᱟᱛᱮ ᱜᱮᱞᱟᱨᱤ ᱠᱷᱚᱱ ᱯᱷᱚᱴᱳ ᱟᱯᱞᱳᱰ ᱢᱮ।",
      cameraStarting: "ᱠᱮᱢᱮᱨᱟ ᱮᱛᱟᱣ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ...",

      locationHeading: "ᱱᱚᱶᱟ ᱚᱠᱟ ᱡᱟᱭᱜᱟ ᱨᱮ ᱦᱩᱭᱩᱜᱼᱟ?",
      locationSub: "ᱟᱢᱟᱜ ᱱᱤᱛᱚᱜ ᱡᱟᱭᱜᱟ ᱵᱮᱵᱚᱦᱟᱨ ᱢᱮ, ᱟᱨᱠᱷᱟᱱ ᱚᱞ ᱠᱟᱛᱮ ᱴᱷᱤᱠᱟᱱᱟ ᱮᱢ ᱢᱮ।",
      gpsButton: "ᱤᱧᱟᱜ ᱱᱤᱛᱚᱜ ᱡᱟᱭᱜᱟ ᱵᱮᱵᱚᱦᱟᱨ ᱢᱮ",
      gpsDetecting: "ᱟᱢᱟᱜ ᱡᱟᱭᱜᱟ ᱧᱟᱢ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ...",
      gpsSuccess: "ᱡᱟᱭᱜᱟ ᱧᱟᱢᱮᱱᱟ",
      gpsFailed: "ᱟᱢᱟᱜ ᱡᱟᱭᱜᱟ ᱵᱟᱭ ᱧᱟᱢᱮᱱᱟ। ᱫᱟᱭᱟ ᱠᱟᱛᱮ ᱞᱟᱛᱟᱨ ᱨᱮ ᱴᱷᱤᱠᱟᱱᱟ ᱚᱞ ᱢᱮ।",
      gpsUnsupported: "ᱱᱚᱶᱟ ᱵᱽᱨᱟᱣᱡᱚᱨ ᱨᱮ ᱡᱟᱭᱜᱟ ᱥᱮᱵᱟ ᱵᱟᱭ ᱫᱟᱲᱮᱭᱟᱜᱼᱟᱱᱟ।",
      addressLabel: "ᱴᱷᱤᱠᱟᱱᱟ / ᱪᱤᱱᱦᱟᱹ",
      addressPlaceholder: "ᱡᱮᱢᱚᱱ: ᱨᱟᱸᱪᱤ ᱵᱚᱥ ᱥᱴᱮᱸᱰ ᱛᱷᱮᱱ, ᱢᱟᱨᱟᱝ ᱜᱟᱰᱤ",
      districtLabel: "ᱡᱤᱞᱟ",
      districtPlaceholder: "ᱟᱢᱟᱜ ᱡᱤᱞᱟ ᱵᱟᱪᱷᱟᱣ ᱢᱮ",
      locationButton: "ᱡᱟᱭᱜᱟ ᱴᱷᱤᱠ ᱢᱮ →",
      locationRequired: "ᱫᱟᱭᱟ ᱠᱟᱛᱮ ᱢᱤᱫ ᱡᱟᱭᱜᱟ ᱟᱨᱠᱷᱟᱱ ᱴᱷᱤᱠᱟᱱᱟ ᱮᱢ ᱢᱮ।",

      reviewHeading: "ᱟᱢᱟᱜ ᱨᱤᱯᱳᱴ ᱧᱮᱞ ᱫᱚᱦᱚ ᱢᱮ",
      reviewSub: "ᱡᱟᱴᱟᱣ ᱦᱚᱸ ᱥᱮᱛᱮᱨ ᱫᱟᱭᱟ ᱠᱟᱛᱮ ᱡᱚᱛᱚ ᱠᱟᱛᱷᱟ ᱧᱮᱞ ᱢᱮ।",
      reviewProblem: "ᱟᱱᱟᱴ",
      reviewCategory: "AI ᱧᱟᱢ ᱠᱟᱛᱮ ᱠᱟᱴᱮᱜᱚᱨᱤ",
      reviewPhoto: "ᱯᱷᱚᱴᱳ",
      reviewLocation: "ᱡᱟᱭᱜᱟ",
      reviewDistrict: "ᱡᱤᱞᱟ",
      reviewEditStep: "ᱥᱟᱯᱲᱟᱣ",
      submitButton: "✓ ᱨᱤᱯᱳᱴ ᱡᱟᱴᱟᱣ ᱢᱮ",
      submitting: "ᱟᱢᱟᱜ ᱨᱤᱯᱳᱴ ᱡᱟᱴᱟᱣ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ...",
      submitFailed: "ᱨᱤᱯᱳᱴ ᱡᱟᱴᱟᱣ ᱵᱟᱭ ᱫᱟᱲᱮᱭᱟᱜᱼᱟᱱᱟ। ᱫᱚᱵᱟᱨ ᱠᱩᱭᱟᱹ ᱧᱮᱞ ᱢᱮ।",

      doneHeading: "ᱨᱤᱯᱳᱴ ᱡᱟᱴᱟᱣ ᱦᱩᱭᱮᱱᱟ",
      ticketIdLabel: "ᱟᱢᱟᱜ ᱴᱤᱠᱮᱴ ᱟᱭᱰᱤ",
      trackButton: "ᱱᱚᱶᱟ ᱟᱨᱡᱤ ᱴᱨᱮᱠ ᱢᱮ",
      newReportButton: "ᱮᱴᱟᱜ ᱟᱱᱟᱴ ᱨᱤᱯᱳᱴ ᱢᱮ",
      whatNextHeading: "ᱛᱟᱭᱚᱢ ᱪᱮᱫ ᱦᱩᱭᱩᱜᱼᱟ?",
      whatNextDedup: "ᱟᱞᱮᱭᱟᱜ ᱥᱤᱥᱴᱚᱢ ᱧᱮᱞ ᱠᱟᱱᱟ ᱪᱤ ᱱᱚᱶᱟ ᱢᱤᱫ ᱛᱮᱦᱮᱸᱱ ᱟᱨᱡᱤ ᱵᱟᱝ ᱠᱟᱱᱟ ᱢᱮᱱᱛᱮ।",
      whatNextPriority: "ᱱᱚᱶᱟ ᱟᱡ ᱛᱮ ᱧᱮᱞ ᱦᱩᱭ ᱠᱟᱛᱮ ᱢᱤᱫ ᱚᱨᱫᱮᱨ ᱮᱢᱚᱜᱼᱟ।",
      whatNextHuman: "ᱡᱟᱴᱟᱣ ᱦᱚᱸ ᱥᱮᱛᱮᱨ ᱢᱤᱫ ᱦᱚᱲ ᱧᱮᱞ ᱠᱟᱛᱮ ᱴᱷᱤᱠ ᱠᱟᱱᱟ।",
      whatNextRoute:
        "ᱱᱚᱶᱟ ᱟᱢᱟᱜ ᱞᱟᱛᱟᱨ ᱢᱩᱱᱥᱤᱯᱟᱞ ᱥᱚᱸᱥᱛᱷᱟ (ᱴᱨᱮᱠ A) ᱛᱮᱸ ᱠᱩᱞ ᱢᱚᱜᱼᱟ, ᱟᱨᱠᱷᱟᱱ ᱢᱟᱨᱟᱝ ᱥᱚᱫᱷᱚᱱᱟ ᱟᱱᱟᱴ ᱞᱟᱹᱜᱤᱫ, ᱢᱤᱫ ᱥᱚᱸᱥᱛᱷᱟ (ᱴᱨᱮᱠ B) ᱛᱮᱸ।",
    },
    track: {
      searchHeading: "ᱟᱢᱟᱜ ᱟᱨᱡᱤ ᱴᱨᱮᱠ ᱢᱮ",
      searchSub: "ᱟᱨᱡᱤ ᱡᱟᱶ ᱠᱟᱛᱮ ᱟᱢ ᱧᱟᱢ ᱞᱮᱫ ᱴᱤᱠᱮᱴ ᱟᱭᱰᱤ ᱚᱞ ᱢᱮ।",
      ticketIdLabel: "ᱴᱤᱠᱮᱴ ᱟᱭᱰᱤ",
      ticketIdPlaceholder: "ᱡᱮᱢᱚᱱ: JH-2026-0001",
      searchButton: "ᱴᱨᱮᱠ",
      notFound: "ᱱᱚᱶᱟ ᱴᱤᱠᱮᱴ ᱟᱭᱰᱤ ᱛᱮ ᱚᱠᱟ ᱦᱮᱸ ᱟᱨᱡᱤ ᱵᱟᱭ ᱧᱟᱢᱮᱱᱟ। ᱫᱟᱭᱟ ᱠᱟᱛᱮ ᱧᱮᱞ ᱠᱟᱛᱮ ᱫᱳᱵᱟᱨ ᱠᱩᱭᱟᱹ ᱧᱮᱞ ᱢᱮ।",
      invalidId: "ᱫᱟᱭᱟ ᱠᱟᱛᱮ ᱢᱤᱫ ᱴᱷᱤᱠ ᱴᱤᱠᱮᱴ ᱟᱭᱰᱤ ᱚᱞ ᱢᱮ।",
      backToSearch: "← ᱮᱴᱟᱜ ᱴᱤᱠᱮᱴ ᱛᱟᱲᱟᱥ ᱢᱮ",
      statusHeading: "ᱟᱨᱡᱤ ᱠᱟᱹᱢᱤ ᱚᱠᱛᱚ",
      problemLabel: "ᱟᱱᱟᱴ",
      categoryLabel: "ᱠᱟᱴᱮᱜᱚᱨᱤ",
      routedToLabel: "ᱚᱠᱟ ᱛᱮᱸ ᱠᱩᱞᱮᱱᱟ",
      timelineHeading: "ᱞᱟᱦᱟ",
      timeline: {
        submitted: "ᱡᱟᱴᱟᱣ ᱦᱩᱭᱮᱱᱟ",
        review: "ᱧᱮᱞ ᱫᱚᱦᱚ ᱨᱮ",
        routed: "ᱠᱩᱞᱮᱱᱟ",
        inProgress: "ᱠᱟᱹᱢᱤ ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟ",
        resolved: "ᱴᱷᱤᱠ ᱦᱩᱭᱮᱱᱟ",
      },
      trackALabel: "ᱴᱨᱮᱠ A · ᱢᱩᱱᱥᱤᱯᱟᱞ ᱥᱚᱸᱥᱛᱷᱟ",
      trackBLabel: "ᱴᱨᱮᱠ B · ᱥᱚᱫᱷᱚᱱᱟ ᱥᱚᱸᱥᱛᱷᱟ",
      reportPhotoLabel: "ᱟᱢ ᱡᱟᱴᱟᱣ ᱞᱮᱫ ᱯᱷᱚᱴᱳ",
      reportPhotoAlt: "ᱱᱚᱶᱟ ᱟᱨᱡᱤ ᱥᱟᱶ ᱡᱟᱴᱟᱣ ᱞᱮᱱ ᱯᱷᱚᱴᱳ",
      closurePhotoLabel: "ᱴᱷᱤᱠ ᱦᱩᱭ ᱞᱮᱱ ᱯᱷᱚᱴᱳ",
      closurePhotoAlt: "ᱟᱱᱟᱴ ᱴᱷᱤᱠ ᱦᱩᱭ ᱞᱮᱱ ᱥᱟᱠᱷᱭᱟᱹᱫ ᱯᱷᱚᱴᱳ",
      institutionLabel: "ᱛᱟᱭᱚᱢ ᱮᱢ ᱠᱟᱱ ᱥᱚᱸᱥᱛᱷᱟ",
      matchStatusLabel: "ᱢᱮᱲᱟᱣ ᱚᱠᱛᱚ",
      proposalStatusLabel: "ᱯᱨᱚᱯᱚᱡᱟᱞ ᱚᱠᱛᱚ",
      milestonesHeading: "ᱥᱚᱫᱷᱚᱱᱟ ᱟᱹᱭᱫᱟᱹ ᱠᱚ",
      pilotVerdictLabel: "ᱯᱟᱭᱞᱚᱴ ᱥᱟᱹᱠᱷᱭᱟᱹᱫ",
    },
    transparency: {
      heading: "ᱯᱟᱨᱥᱤᱭᱟᱹᱛᱟᱹ ᱰᱮᱥᱵᱳᱨᱰ",
      sub: "ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱨᱮ ᱟᱨᱡᱤ ᱠᱚ ᱪᱮᱫ ᱞᱮᱠᱟ ᱴᱷᱤᱠ ᱦᱩᱭᱩᱜᱼᱟ ᱚᱱᱟᱨᱮᱭᱟᱜ ᱡᱚᱛᱚ ᱞᱟᱹᱜᱤᱫ ᱰᱟᱴᱟ।",
      dataNote: "ᱡᱚᱛᱚ ᱦᱤᱥᱟᱹᱵ ᱡᱚᱲᱟᱣ ᱠᱟᱛᱮ ᱚᱠᱛᱚ ᱛᱮ ᱟᱭᱩᱛ ᱦᱩᱭᱩᱜᱼᱟ। ᱚᱠᱟ ᱦᱮᱸ ᱦᱚᱲ ᱨᱮᱭᱟᱜ ᱵᱮᱠᱛᱤᱜᱚᱛ ᱰᱟᱴᱟ ᱵᱟᱭ ᱫᱮᱠᱷᱟᱣᱮᱱᱟ।",
      statsHeading: "ᱡᱚᱛᱚ ᱧᱮᱞ",
      statFiled: "ᱡᱟᱶ ᱟᱨᱡᱤ ᱠᱚ",
      statResolved: "ᱴᱷᱤᱠ ᱦᱩᱭ ᱞᱮᱱ ᱟᱨᱡᱤ ᱠᱚ",
      statDistricts: "ᱛᱟᱦᱮᱸᱱ ᱡᱤᱞᱟ ᱠᱚ",
      statInstitutions: "ᱡᱩᱲᱟᱶ ᱠᱟᱱ ᱥᱚᱸᱥᱛᱷᱟ ᱠᱚ",
      districtHeading: "ᱡᱤᱞᱟ ᱞᱮᱠᱟᱛᱮ ᱟᱨᱡᱤ ᱠᱚ",
      categoryHeading: "ᱠᱟᱴᱮᱜᱚᱨᱤ ᱞᱮᱠᱟᱛᱮ ᱟᱨᱡᱤ ᱠᱚ",
      trackSplitHeading: "ᱴᱨᱮᱠ A ᱡᱟᱦᱟᱸ ᱴᱨᱮᱠ B",
      trackSplitSub: "ᱢᱩᱱᱥᱤᱯᱟᱞ ᱠᱟᱹᱢᱤ ᱡᱟᱦᱟᱸ ᱥᱚᱫᱷᱚᱱᱟ-ᱥᱚᱸᱥᱛᱷᱟ ᱠᱟᱹᱢᱤ।",
      resolutionHeading: "ᱴᱷᱤᱠ ᱦᱩᱭ ᱞᱮᱱ ᱡᱚᱜᱟᱨ",
      resolutionPassed: "ᱥᱟᱹᱠᱷᱭᱟᱹᱫ ᱥᱟᱶ ᱴᱷᱤᱠ ᱦᱩᱭᱮᱱᱟ",
      resolutionFailed: "ᱥᱟᱹᱠᱷᱭᱟᱹᱫ ᱵᱟᱭ ᱴᱷᱤᱠᱮᱱᱟ",
      resolutionPending: "ᱥᱟᱹᱠᱷᱭᱟᱹᱫ ᱞᱟᱦᱟ ᱛᱟᱦᱮᱸᱱᱟᱜ",
      demoNotice: "ᱰᱮᱢᱳ ᱰᱟᱴᱟ ᱫᱮᱠᱷᱟᱣᱠᱟᱱᱟ — ᱱᱤᱛᱚᱜ ᱵᱮᱠᱮᱸᱰ ᱛᱟᱲᱟᱨ ᱦᱩᱭ ᱵᱟᱭ ᱫᱟᱲᱮᱭᱟᱜᱼᱟᱱᱟ।",
      moreDepthLink: "ᱰᱤᱯᱟᱨᱴᱢᱮᱸᱴ/ᱴᱨᱮᱠ ᱥᱮᱛᱮᱨ ᱟᱨᱦᱚᱸ ᱵᱟᱰᱟᱭ ᱡᱟᱹᱨᱩᱨᱤ ᱟ? ᱡᱚᱛᱚ ᱥᱚᱨᱠᱟᱨ ᱰᱮᱥᱵᱳᱨᱰ ᱧᱮᱞ ᱢᱮ।",
    },
    about: {
      heading: "ᱥᱟᱦᱭᱳᱜ ᱵᱟᱵᱚᱛ",
      intro:
        "ᱥᱟᱦᱭᱳᱜ ᱢᱤᱫ ᱵᱟᱦᱟ ᱨᱚᱲ, AI ᱫᱟᱲᱮᱭᱟᱜ ᱠᱟᱱ ᱯᱞᱮᱴᱯᱷᱚᱨᱚᱢ ᱠᱟᱱᱟ ᱡᱟᱦᱟᱸ ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱨᱮᱭᱟᱜ ᱦᱚᱲ ᱠᱚ ᱡᱤᱣᱚᱱ ᱟᱱᱟᱴ ᱨᱤᱯᱳᱴ ᱫᱟᱲᱮᱭᱟᱜᱚᱜᱼᱟ ᱟᱨ ᱥᱚᱨᱠᱟᱨ ᱡᱟᱭᱜᱟᱭ ᱟᱨ ᱴᱷᱤᱠ ᱴᱷᱤᱠ ᱡᱚᱵᱟᱵ ᱮᱢ ᱨᱮ ᱜᱚᱲᱚᱭᱚᱜᱼᱟ।",
      howHeading: "ᱱᱚᱶᱟ ᱪᱮᱫ ᱞᱮᱠᱟᱛᱮ ᱠᱟᱹᱢᱤ ᱮᱫᱟ",
      howIntro: "AI ᱜᱚᱲᱚᱭᱚᱜᱼᱟ — ᱴᱷᱤᱠ ᱦᱚᱲ ᱠᱚ ᱛᱮ ᱛᱟᱦᱮᱸᱱᱟ। ᱡᱚᱛᱚ ᱟᱹᱭᱫᱟᱹ ᱨᱮ, ᱠᱟᱹᱢᱤ ᱦᱚᱸ ᱥᱮᱛᱮᱨ ᱢᱤᱫ ᱦᱚᱲ ᱧᱮᱞ ᱠᱟᱛᱮ ᱴᱷᱤᱠᱚᱜᱼᱟ।",
      step1Title: "1. ᱟᱢ ᱟᱱᱟᱴ ᱵᱟᱰᱟᱭ ᱫᱟᱲᱮᱭᱟᱜᱢᱮ",
      step1Body:
        "ᱟᱢᱟᱜ ᱚᱲᱟᱜ ᱠᱟᱛᱷᱟ ᱛᱮ, ᱟᱢᱟᱜ ᱚᱲᱟᱜ ᱨᱚᱲ ᱛᱮ, ᱚᱞ ᱠᱟᱛᱮ ᱟᱨᱠᱷᱟᱱ ᱠᱟᱛᱷᱟ ᱛᱮ। ᱟᱞᱮᱭᱟᱜ ᱥᱤᱥᱴᱚᱢ ᱚᱱᱟ ᱯᱟᱰᱷᱟᱶ ᱟᱨᱠᱷᱟᱱ ᱟᱭᱩᱢ ᱠᱟᱛᱮ ᱠᱟᱴᱮᱜᱚᱨᱤ ᱟᱨ ᱢᱟᱨᱟᱝ ᱨᱚᱠᱚᱢ ᱟᱡ ᱛᱮ ᱧᱟᱢᱚᱜᱼᱟ — ᱟᱢ ᱠᱚᱸ ᱚᱱᱟ ᱠᱟᱴᱮᱜᱚᱨᱤ ᱵᱟᱪᱷᱟᱣ ᱞᱟᱹᱜᱤᱫ ᱵᱟᱭ ᱡᱟᱹᱨᱩᱨᱤᱭᱟ।",
      step2Title: "2. ᱟᱞᱮ ᱢᱮᱲᱟᱣ ᱟᱨᱡᱤ ᱧᱮᱞ ᱦᱩᱭᱩᱜᱼᱟ",
      step2Body:
        "ᱢᱤᱫᱴᱟᱝ ᱟᱱᱟᱴ ᱞᱟᱹᱜᱤᱫ ᱢᱤᱫ ᱠᱷᱚᱱ ᱰᱷᱮᱨ ᱴᱤᱠᱮᱴ ᱵᱟᱭ ᱦᱩᱭ ᱞᱟᱹᱜᱤᱫ, ᱥᱤᱥᱴᱚᱢ ᱟᱢᱟᱜ ᱟᱨᱡᱤ ᱚᱱᱟ ᱡᱟᱭᱜᱟ ᱨᱮᱭᱟᱜ ᱛᱟᱦᱮᱸᱱ ᱟᱨᱡᱤ ᱠᱚ ᱥᱟᱶ ᱡᱟᱪᱟᱣᱚᱜᱼᱟ।",
      step3Title: "3. ᱚᱨᱫᱮᱨ ᱮᱢᱚᱜᱼᱟ",
      step3Body:
        "ᱢᱟᱨᱟᱝ ᱨᱚᱠᱚᱢ, ᱡᱟᱭᱜᱟ ᱟᱨ ᱠᱟᱴᱮᱜᱚᱨᱤ ᱞᱮᱠᱟᱛᱮ ᱟᱨᱡᱤ ᱨᱮ ᱢᱤᱫ ᱚᱨᱫᱮᱨ ᱮᱢᱚᱜᱼᱟ ᱡᱟᱦᱟᱸᱛᱮ ᱡᱟᱹᱨᱩᱨᱤ ᱟᱱᱟᱴ ᱠᱚ ᱞᱟᱭᱤᱱ ᱨᱮ ᱵᱟᱭ ᱦᱚᱲᱚᱠᱟ।",
      step4Title: "4. ᱢᱤᱫ ᱦᱚᱲ ᱧᱮᱞ ᱫᱚᱦᱚᱭᱟ, ᱚᱲᱦᱚᱸ ᱠᱩᱞᱚᱜᱼᱟ",
      step4Body:
        "ᱥᱤᱠᱷᱚᱸ ᱠᱟᱱ ᱦᱚᱲ ᱢᱤᱫ ᱡᱟᱪᱟᱣ ᱧᱮᱞᱚᱜᱼᱟ। ᱦᱟᱹᱨ ᱟᱹᱭᱫᱟᱹ ᱠᱟᱱ ᱟᱱᱟᱴ ᱠᱚ ᱞᱟᱛᱟᱨ ᱢᱩᱱᱥᱤᱯᱟᱞ ᱥᱚᱸᱥᱛᱷᱟ (ᱴᱨᱮᱠ A) ᱛᱮᱸ ᱠᱩᱞᱚᱜᱼᱟ; ᱢᱟᱨᱟᱝ ᱟᱨᱠᱷᱟᱱ ᱥᱚᱫᱷᱚᱱᱟ ᱡᱚᱜᱟᱭ ᱟᱱᱟᱴ ᱠᱚ ᱥᱚᱫᱷᱚᱱᱟ ᱥᱚᱸᱥᱛᱷᱟ (ᱴᱨᱮᱠ B) ᱛᱮᱸ ᱠᱩᱞ ᱫᱟᱲᱮᱭᱟᱜᱼᱟ।",
      contactHeading: "ᱠᱩᱥᱤᱭᱟᱹᱨ ᱟᱨᱠᱷᱟᱱ ᱟᱢᱟᱜ ᱵᱟᱰᱟᱭ?",
      contactBody: "ᱡᱟᱶ ᱞᱮᱱ ᱟᱨᱡᱤ ᱧᱮᱞ ᱞᱟᱹᱜᱤᱫ 'ᱟᱨᱡᱤ ᱴᱨᱮᱠ ᱢᱮ' ᱵᱮᱵᱚᱦᱟᱨ ᱢᱮ। ᱱᱟᱶᱟ ᱟᱱᱟᱴ ᱨᱤᱯᱳᱴ ᱞᱟᱹᱜᱤᱫ 'ᱡᱟᱶ ᱨᱤᱯᱳᱴ ᱢᱮ' ᱵᱮᱵᱚᱦᱟᱨ ᱢᱮ।",
    },
  },
};

// Dot-path lookup, e.g. t("home.heroTitle"). Falls back to English, then to
// the raw path, so a missing translation never renders a blank string -
// this is also what quietly restricts operator/institution/government
// content to English/Hindi even though those namespaces exist only in the
// "en" and "hi" blocks above: any other active language falls through to
// English for those keys automatically.
export function translate(lang, path) {
  const parts = path.split(".");

  let node = dict[lang];
  for (const p of parts) node = node?.[p];
  if (node != null) return node;

  let en = dict.en;
  for (const p of parts) en = en?.[p];
  return en ?? path;
}
